In [1]:
from dataraum import Context

# Test basic usage
ctx = Context("./pipeline_output")

# Test tables list
print(ctx.tables)

# Test entropy
print(ctx.entropy.summary())

# Test contracts
print(ctx.contracts.list())
print(ctx.contracts.evaluate("aggregation_safe"))

# Test context document
print(ctx.context_document())

# Test query (requires LLM configured)
# result = ctx.query("What tables are available?")
# result.to_dataframe()

# Clean up
ctx.close()

<frozen importlib._bootstrap>:491: RuntimeWarning: The global interpreter lock (GIL) has been enabled to load module '_duckdb', which has not declared that it can run safely without the GIL. To override this behavior and keep the GIL disabled (at your own risk), run with PYTHON_GIL=0 or -Xgil=0.

['kontobuchungen', 'kontobuchungen', 'kontobuchungen', 'slice_herkunftskennzeichen_sv', 'slice_herkunftskennzeichen_re', 'slice_herkunftskennzeichen_an', 'slice_herkunftskennzeichen_fy', 'slice_herkunftskennzeichen_wk', 'slice_herkunftskennzeichen_zv', 'slice_waehungskz_eingegebener_umsatz_eur', 'slice_waehungskz_eingegebener_umsatz_chf', 'slice_waehungskz_eingegebener_umsatz_cad', 'slice_eingegebenr_umsatz_sollhaben_kennzeichen_s', 'slice_eingegebenr_umsatz_sollhaben_kennzeichen_h', 'slice_wirtschaftsjahres_monat_1', 'slice_wirtschaftsjahres_monat_2', 'slice_wirtschaftsjahres_monat_3']
{'source': 'kontobuchungen', 'overall_readiness': 'ready', 'composite_score': 0.15064283792434993, 'dimensions': {'structural': 0.018103907811703835, 'semantic': 0.23387096774193547, 'value': 0.2519805774851686, 'computational': 0.002409316021951541}, 'columns': [{'table': 'kontobuchungen', 'column': 'Berichtigungs_Umsatzsteuerschlüssel', 'score': 0.3011854103343465, 'readiness': 'investigate', 'explanation': "This VAT adjustment tax code has significant uncertainty (0.301 composite score) with 'investigate' readiness status. The critical issues are 100% null ratio and 60.8% outlier rate, suggesting this is a rarely-used field for special tax corrections. The high value entropy (0.804) indicates most transactions don't require tax adjustments, but when values exist, they may be unusual codes requiring special handling."}, {'table': 'kontobuchungen', 'column': 'Umsatz Soll', 'score': 0.3, 'readiness': 'investigate', 'explanation': "This debit amount column has a composite score of 0.30 and readiness status 'investigate', indicating moderate uncertainty. The main issues are: (1) 100% outlier rate suggesting all values are flagged as unusual, and (2) high semantic.units.unit_declaration entropy (0.8), meaning the unit (cents/pfennigs) is not clearly declared. This creates risk for financial calculations."}, {'table': 'kontobuchungen', 'column': 'Umsatz Haben', 'score': 0.3, 'readiness': 'investigate', 'explanation': "This credit amount column has moderate uncertainty (0.3 composite score). While structurally sound, it suffers from high outlier rates (1.0) and unclear unit declaration (0.8). The business description indicates values are in smallest currency units (cents/pfennigs), but this critical metadata isn't formally declared, creating semantic ambiguity for calculations."}, {'table': 'kontobuchungen', 'column': 'Buchungstext', 'score': 0.260390340218712, 'readiness': 'ready', 'explanation': 'This transaction description text field has moderate uncertainty (0.26 composite score) with significant issues: 51.1% null values and 49.5% structural type fidelity concerns. Over half the transactions lack descriptive text, reducing auditability and analysis capabilities. The structural entropy suggests potential encoding issues or inconsistent text formats.'}, {'table': 'kontobuchungen', 'column': 'Kennung EB-Buchung', 'score': 0.22448967193195626, 'readiness': 'ready', 'explanation': "This opening balance indicator flag has moderate uncertainty (0.224 composite score, 'ready' status). The critical issue is 100% outlier rate, suggesting all values are flagged as unusual - likely because opening balance entries are rare compared to regular transactions. With 9.7% nulls and clear binary semantics (0/1 flag), the column is usable but the outlier detection may need recalibration."}, {'table': 'kontobuchungen', 'column': 'Kontonummer des Gegenkontos', 'score': 0.21, 'readiness': 'ready', 'explanation': 'This offsetting account number column shows concerning data quality (0.21 composite score) with 100% outlier rate, indicating the entire dataset may contain unusual account numbers, possibly including special accounts, placeholder values, or a non-standard account numbering scheme. The high value entropy (0.5) requires investigation before reliable use.'}, {'table': 'kontobuchungen', 'column': 'Kontobewegung Steuersatz', 'score': 0.21, 'readiness': 'ready', 'explanation': "This tax rate column has a composite score of 0.21 and is marked 'ready'. The critical issue is a perfect 1.0 outlier rate, indicating all values are flagged as outliers. Given the business description states values are in basis points (e.g., 1900 = 19%), this likely reflects the wide range of tax rates or the encoding method being misinterpreted by outlier detection. No nulls present."}, {'table': 'kontobuchungen', 'column': 'Kontonummer des Kontos', 'score': 0.21, 'readiness': 'ready', 'explanation': "This general ledger account number column has a composite score of 0.21 and is 'ready'. The main concern is a perfect 1.0 outlier rate, meaning all account numbers are flagged as outliers. This is likely a false positive from outlier detection not being calibrated for account number ranges. No nulls (0.0) indicates complete data. The BIGINT type is appropriate for numeric account codes."}, {'table': 'kontobuchungen', 'column': 'Belegfeld 2', 'score': 0.21, 'readiness': 'ready', 'explanation': "This supplementary document field has moderate uncertainty (0.21 composite score, 'ready' status). The critical issue is 100% null ratio, meaning the column is completely empty. This suggests it's either unused, optional for rare cases, or represents missing data. The semantic meaning is also vague ('supplementary information'), making it unclear when this field should be populated."}, {'table': 'kontobuchungen', 'column': 'Leistungsdatum', 'score': 0.195, 'readiness': 'ready', 'explanation': "This service/delivery date column has a composite score of 0.195 and is 'ready'. The critical issue is a perfect 1.0 null ratio, meaning this date is completely unpopulated across all records. This is concerning for tax and revenue recognition purposes as stated in the business description. The DATE type is correct, and semantic entropy is low (0.15) due to clear temporal meaning."}, {'table': 'kontobuchungen', 'column': 'Faelligkeitsdatum der Buchung', 'score': 0.195, 'readiness': 'ready', 'explanation': "This payment due date column has moderate uncertainty (0.195 composite score, 'ready' status). The main issue is 100% null ratio, meaning no due dates are recorded. This is problematic for a field described as being used for 'cash flow planning and aging analysis'. The semantic entropy is low (0.15) due to clear temporal meaning, but the complete absence of data raises questions about data completeness."}, {'table': 'kontobuchungen', 'column': 'ID des Rechnungslegungsbereichs', 'score': 0.18029161603888214, 'readiness': 'ready', 'explanation': "This accounting area identifier has excellent structural quality (BIGINT type) but shows a very high outlier rate (0.802), suggesting the distribution of accounting area IDs is highly skewed or contains unusual values. The column name has minor clarity issues. The data is marked 'ready' with a low composite score of 0.18, indicating it's usable but requires attention to the outlier pattern."}, {'table': 'kontobuchungen', 'column': 'Kost1Kostenstelle', 'score': 0.17682867557715673, 'readiness': 'ready', 'explanation': "This cost center column has a composite score of 0.177 and is 'ready'. The dominant issue is a very high null ratio of 77.9%, indicating that most postings don't have cost center assignments. This is common in accounting systems where cost center allocation is optional or only applies to certain account types. No outliers detected (0.0 rate) suggests the populated values are consistent."}, {'table': 'kontobuchungen', 'column': 'Bearbeitungsstatus', 'score': 0.17215963682183816, 'readiness': 'ready', 'explanation': "This processing status code column has a composite score of 0.172 and is 'ready'. It shows moderate value entropy (0.374) driven by a 65.1% outlier rate and 9.7% null ratio. The nulls suggest some postings lack status information, while the high outlier rate may indicate rare status codes or data quality issues. The BIGINT type is appropriate for status codes."}, {'table': 'kontobuchungen', 'column': 'Eingegebener Umsatz', 'score': 0.1687741495986556, 'readiness': 'ready', 'explanation': "This transaction amount column has moderate uncertainty (0.169 composite score) primarily due to missing unit declaration (0.8 semantic entropy). While stored as BIGINT, it's unclear whether values represent cents/smallest currency unit or if decimal scaling is applied. The 11.2% outlier rate and lack of unit metadata create computational risks when performing calculations."}, {'table': 'kontobuchungen', 'column': 'Umrechnungskurs', 'score': 0.1687741495986556, 'readiness': 'ready', 'explanation': "This currency conversion rate column has low-moderate uncertainty (0.169 composite score, 'ready' status). The main issue is high semantic entropy (0.5) due to unclear unit declaration (0.8) - it's stored as BIGINT but described as a 'multiplier', creating ambiguity about the scale factor. Value quality is good with minimal outliers (11.2%)."}, {'table': 'kontobuchungen', 'column': 'Folgebuchungsatzzaehler', 'score': 0.13098504378002518, 'readiness': 'ready', 'explanation': 'This follow-up posting counter has low-moderate uncertainty (0.131 composite score). The 9.7% null ratio suggests most transactions are simple single postings, while 37.7% outlier rate indicates some complex multi-part transactions. The data is generally usable but requires assumptions about null handling and outlier interpretation.'}, {'table': 'kontobuchungen', 'column': 'Kontobewegungstyp', 'score': 0.11757936232455121, 'readiness': 'ready', 'explanation': "This transaction type classification column is in good shape (0.118 composite score, 'ready' status). It has minimal nulls (9.7%) and moderate outliers (28.7%), with slight naming clarity issues due to German terminology. The column is usable but would benefit from documentation of the type codes and null handling."}, {'table': 'kontobuchungen', 'column': 'Belegnummer', 'score': 0.10666886306267989, 'readiness': 'ready', 'explanation': "This document number column has low uncertainty (0.107 composite score, 'ready' status). It shows good overall quality with minor issues: 13.2% nulls, 6.8% outliers, and slight type fidelity concerns (0.066) suggesting some values may not parse cleanly as BIGINT. As a unique identifier for source documents, the nulls are concerning for traceability."}, {'table': 'kontobuchungen', 'column': 'Buchungssatznummer', 'score': 0.08015770853831687, 'readiness': 'ready', 'explanation': 'This posting line number has very low uncertainty (0.08 composite score) and is highly usable. The 9.4% outlier rate suggests some documents have unusually many line items, which is likely valid for complex transactions. Minor computational entropy (0.04) indicates the sequential numbering is mostly consistent but may have gaps or non-sequential patterns.'}, {'table': 'kontobuchungen', 'column': 'Generalumkehr (GU)', 'score': 0.07764958256074656, 'readiness': 'ready', 'explanation': "This reversal flag has very low uncertainty (0.078 composite score) and is highly reliable. The 9.7% null ratio requires clarification on whether nulls mean 'not a reversal' or 'unknown'. The minimal outlier rate (1.9%) and low computational entropy indicate the flag is consistently used and reliable for calculations."}, {'table': 'kontobuchungen', 'column': 'EU Steuersatz', 'score': 0.0765454056085437, 'readiness': 'ready', 'explanation': "This EU tax rate column is in excellent condition (0.077 composite score, 'ready' status). Stored as basis points with minimal outliers (10.3%) and very low null ratio. The main uncertainty is minor naming clarity and a small computational formula mismatch (0.7%), suggesting the column is reliable for analysis with minimal assumptions needed."}, {'table': 'kontobuchungen', 'column': 'Rolle desw Kontos im Buchungssatz', 'score': 0.07448967193195626, 'readiness': 'ready', 'explanation': "This debit/credit role indicator has very low uncertainty (0.074 composite score) and is highly usable. The 9.7% null ratio is the only concern, likely representing transactions where the role wasn't explicitly recorded. The column name has a typo ('desw' instead of 'des'), contributing to minor naming clarity issues."}, {'table': 'kontobuchungen', 'column': 'Belegidentifikator', 'score': 0.07448967193195626, 'readiness': 'ready', 'explanation': 'This document identifier has very low uncertainty (0.074 composite score) and is highly reliable for grouping related postings. The 9.7% null ratio is the only concern, potentially indicating orphaned postings or system-generated entries without document references. Overall, the column is ready for use with minimal assumptions.'}, {'table': 'kontobuchungen', 'column': 'Stapelidentifikator', 'score': 0.07448967193195626, 'readiness': 'ready', 'explanation': "This batch identifier column has an excellent composite score of 0.074 and is 'ready'. It shows very low value entropy (0.048) with only 9.7% nulls and no outliers. The BIGINT type is appropriate for numeric batch IDs. The minor null ratio suggests most postings are properly batched, with a small percentage potentially being individual/manual entries. Overall, this is high-quality data."}, {'table': 'kontobuchungen', 'column': 'Herkunftskennzeichen', 'score': 0.07448967193195626, 'readiness': 'ready', 'explanation': "This source system identifier column has an excellent composite score of 0.074 and is 'ready'. It shows very low value entropy (0.048) with only 9.7% nulls and no outliers. The VARCHAR type is appropriate for system codes. The business description lists valid codes (SV, RE, AN, FY, WK, ZV), suggesting a well-defined value set. The minor null ratio may represent legacy data or manual entries."}, {'table': 'kontobuchungen', 'column': 'Wirtschaftsjahres Monat', 'score': 0.07448967193195626, 'readiness': 'ready', 'explanation': "This fiscal year month column is in excellent condition (0.074 composite score, 'ready' status). It has minimal uncertainty with only 9.7% nulls, no outliers, and clear semantic meaning as a month number (1-12). The column is highly reliable for period-based reporting with minimal assumptions needed."}, {'table': 'kontobuchungen', 'column': 'WaehungsKZ Eingegebener Umsatz', 'score': 0.06, 'readiness': 'ready', 'explanation': "This currency code column is in excellent condition with a composite score of 0.06. The only minor uncertainty is in naming clarity (0.2 semantic entropy), likely due to the German abbreviation 'WaehungsKZ'. The data is complete, structurally sound, and ready for use with minimal assumptions needed."}, {'table': 'kontobuchungen', 'column': 'Eingegebenr Umsatz SollHaben Kennzeichen', 'score': 0.06, 'readiness': 'ready', 'explanation': 'This debit/credit flag column has excellent data quality with a very low composite score of 0.06. No nulls, no outliers, and proper VARCHAR type. The only minor issue is a slight naming clarity concern (0.2), likely due to the German naming convention. The column is fully ready for use.'}, {'table': 'kontobuchungen', 'column': 'Stapelnummer', 'score': 0.06, 'readiness': 'ready', 'explanation': "This batch identifier column is in excellent condition (0.06 composite score, 'ready' status). It has the lowest uncertainty of all columns with no nulls, no outliers, and clear structure (MM-YYYY/sequence format). The only minor issue is naming clarity (0.2) due to German terminology, but the column is highly reliable for grouping related postings."}, {'table': 'kontobuchungen', 'column': 'Belegdatum der Buchung', 'score': 0.045000000000000005, 'readiness': 'ready', 'explanation': "This DATE column has excellent overall data quality (composite score: 0.045) and is marked as 'ready' for use. The data is structurally sound with perfect type fidelity, complete with no nulls, and free of outliers. The only minor uncertainty comes from semantic dimensions: slight ambiguity in naming clarity (0.2) and temporal role definition (0.1). The German column name 'Belegdatum der Buchung' (document date of the posting) is descriptive but could benefit from standardization regarding timezone assumptions and whether this represents transaction date, posting date, or value date in accounting terms."}, {'table': 'kontobuchungen', 'column': None, 'score': 0.0, 'readiness': 'investigate', 'explanation': 'The kontobuchungen table exhibits a critical data quality paradox: while achieving perfect dimensional entropy scores (0.00) across all 27 categorical columns, this reflects severe data concentration rather than quality excellence. Specifically, 83% of the 3,133 records are concentrated in a single slice (SV), with one slice containing only 3 records, creating statistically unreliable segmentation. The analysis is further hampered by incomplete metadata across 10 columns (37% of the dataset), where missing null ratios and distinct value counts prevent validation of critical business rules such as referential integrity for foreign keys, proper flag values, and temporal consistency between service and due dates. This combination of extreme slice imbalance and metadata gaps poses significant risks to financial reporting accuracy and audit compliance for this accounting transaction dataset.'}]}
[{'name': 'exploratory_analysis', 'display_name': 'Exploratory Analysis', 'description': 'For data exploration, hypothesis testing, initial analysis', 'overall_threshold': 0.5}, {'name': 'data_science', 'display_name': 'Data Science / ML', 'description': 'For feature engineering, model training, statistical analysis', 'overall_threshold': 0.35}, {'name': 'operational_analytics', 'display_name': 'Operational Analytics', 'description': 'For operational reports, team dashboards, process monitoring', 'overall_threshold': 0.35}, {'name': 'executive_dashboard', 'display_name': 'Executive Dashboard', 'description': 'For C-level dashboards, board presentations, KPI tracking', 'overall_threshold': 0.25}, {'name': 'regulatory_reporting', 'display_name': 'Regulatory Reporting', 'description': 'For financial statements, compliance reports, audit submissions', 'overall_threshold': 0.1}]
{'error': 'Contract not found: aggregation_safe'}
## DATASET CONTEXT

- Tables: 17
- Columns: 566
- Relationships: 0
- Graph pattern: disconnected

## QUALITY SUMMARY
- critical: 24 issues
- warning: 6 issues

## DATA READINESS: ✓ READY
Data quality is sufficient for reliable answers.

## TABLES

### kontobuchungen
Rows: 3,292

Columns:
  - ID des Rechnungslegungsbereichs (BIGINT)
  - Kontonummer des Kontos (BIGINT)
  - Belegdatum der Buchung (DATE)
  - Berichtigungs_Umsatzsteuerschlüssel (BIGINT)
  - Kontonummer des Gegenkontos (BIGINT)
  - Buchungstext (VARCHAR)
  - Kontobewegung Steuersatz (BIGINT)
  - EU Steuersatz (BIGINT)
  - Belegnummer (BIGINT)
  - Belegfeld 2 (BIGINT)
  - Umsatz Soll (BIGINT)
  - Umsatz Haben (BIGINT)
  - Eingegebenr Umsatz SollHaben Kennzeichen (VARCHAR)
  - Eingegebener Umsatz (BIGINT)
  - WaehungsKZ Eingegebener Umsatz (VARCHAR)
  - Umrechnungskurs (BIGINT)
  - Basiswaehrung (VARCHAR)
  - Stapelnummer (VARCHAR)
  - Buchungssatznummer (BIGINT)
  - Kost1Kostenstelle (BIGINT)
  - Kost2Kostenstelle (VARCHAR)
  - Kost Mengenfeld (BIGINT)
  - Kennung EB-Buchung (BIGINT)
  - Wirtschaftsjahres Monat (BIGINT)
  - Buchungstyp (BIGINT)
  - Bearbeitungsstatus (BIGINT)
  - Belegpruefungsstatus (BIGINT)
  - Kontobewegungstyp (BIGINT)
  - Rolle desw Kontos im Buchungssatz (BIGINT)
  - Folgebuchungsatzzaehler (BIGINT)
  - Abweichende Besteuerungsart (VARCHAR)
  - Sachverhalt Lieferungen und Leistungen (BIGINT)
  - Funktionsergaenzung Lieferungen und Leistungen (BIGINT)
  - Hauptfunktionstyp Steuerschluessel 49 (BIGINT)
  - Hauptfunktionsnummer Steuerschluessel 49 (BIGINT)
  - Funktionsergaenzung Steuerschluessel 49 (BIGINT)
  - Herkunftskennzeichen (VARCHAR)
  - Beleglink (VARCHAR)
  - Stapelidentifikator (BIGINT)
  - Belegidentifikator (BIGINT)
  - Stueck (VARCHAR)
  - Gewicht (VARCHAR)

In [3]:
ctx.contracts.list()

[{'name': 'exploratory_analysis',
  'display_name': 'Exploratory Analysis',
  'description': 'For data exploration, hypothesis testing, initial analysis',
  'overall_threshold': 0.5},
 {'name': 'data_science',
  'display_name': 'Data Science / ML',
  'description': 'For feature engineering, model training, statistical analysis',
  'overall_threshold': 0.35},
 {'name': 'operational_analytics',
  'display_name': 'Operational Analytics',
  'description': 'For operational reports, team dashboards, process monitoring',
  'overall_threshold': 0.35},
 {'name': 'executive_dashboard',
  'display_name': 'Executive Dashboard',
  'description': 'For C-level dashboards, board presentations, KPI tracking',
  'overall_threshold': 0.25},
 {'name': 'regulatory_reporting',
  'display_name': 'Regulatory Reporting',
  'description': 'For financial statements, compliance reports, audit submissions',
  'overall_threshold': 0.1}]

In [5]:
ctx.contracts.evaluate("regulatory_reporting")

{'contract': 'regulatory_reporting',
 'is_compliant': False,
 'confidence_level': 'red',
 'overall_score': 0.14489818477330918,
 'dimension_scores': {'structural.types': 0.018103907811703835,
  'structural.relations': 0.018103907811703835,
  'semantic.business_meaning': 0.2,
  'semantic.units': 0.24543010752688174,
  'semantic.temporal': 0.18510752688172044,
  'semantic.dimensional': 0.13096774193548388,
  'value.nulls': 0.20607141457296282,
  'value.outliers': 0.2978897403973745,
  'computational.derived_values': 0.002409316021951541},
 'violations': [{'dimension': 'semantic.business_meaning',
   'actual': 0.2,
   'max_allowed': 0.1,
   'details': 'semantic.business_meaning score 0.20 exceeds threshold 0.10'},
  {'dimension': 'semantic.units',
   'actual': 0.24543010752688174,
   'max_allowed': 0.1,
   'details': 'semantic.units score 0.25 exceeds threshold 0.10'},
  {'dimension': 'semantic.temporal',
   'actual': 0.18510752688172044,
   'max_allowed': 0.1,
   'details': 'semantic.temporal score 0.19 exceeds threshold 0.10'},
  {'dimension': 'value.nulls',
   'actual': 0.20607141457296282,
   'max_allowed': 0.1,
   'details': 'value.nulls score 0.21 exceeds threshold 0.10'},
  {'dimension': 'value.outliers',
   'actual': 0.2978897403973745,
   'max_allowed': 0.2,
   'details': 'value.outliers score 0.30 exceeds threshold 0.20'},
  {'dimension': None,
   'actual': 0.14489818477330918,
   'max_allowed': 0.1,
   'details': 'Overall entropy 0.14 exceeds threshold 0.10'},
  {'dimension': None,
   'actual': None,
   'max_allowed': None,
   'details': 'Any dimension exceeding 0.2 blocks regulatory reporting'}],
 'warnings': [{'details': 'semantic.dimensional score 0.13 exceeds threshold 0.10'}]}

In [9]:
# print(ctx.context_document())
# Test query (requires LLM configured)
result = ctx.query("What is the short-term cash flow?")
result.to_dataframe()

Batches: 100%|██████████| 1/1 [00:00<00:00,  2.17it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 33.74it/s]
HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.38it/s]
2026-02-09T11:25:39.505058Z [info     ] Saved query to library: 6eda46f4-6a8f-4312-a95e-b83a937afb30

   short_term_cash_flow
0                856.43

In [24]:
# Query all SQLite tables (metadata database)
import json
import sqlite3
from pathlib import Path

output_dir = Path("./pipeline_output")
sqlite_path = output_dir / "metadata.db"

conn = sqlite3.connect(sqlite_path)
cursor = conn.cursor()

# Get all table names
cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
tables = cursor.fetchall()

print("=== SQLite Tables (Metadata) ===")
for t in tables:
    table_name = t[0]
    cursor.execute(f"SELECT COUNT(*) FROM {table_name}")
    count = cursor.fetchone()[0]
    print(f"  {table_name}: {count} rows")

conn.close()

=== SQLite Tables (Metadata) ===
  business_cycle_analysis_runs: 1 rows
  categorical_associations: 2 rows
  column_correlations: 30 rows
  column_eligibility: 50 rows
  column_quality_reports: 54 rows
  column_slice_profiles: 243 rows
  columns: 566 rows
  compound_risks: 0 rows
  correlation_analysis_runs: 1 rows
  correlation_quality_issues: 0 rows
  cross_table_correlations: 0 rows
  derived_columns: 198 rows
  detected_business_cycles: 0 rows
  entropy_interpretations: 32 rows
  entropy_objects: 165 rows
  entropy_snapshots: 1 rows
  functional_dependencies: 148 rows
  generated_code: 7 rows
  graph_executions: 6 rows
  llm_cache: 0 rows
  multicollinearity_groups: 0 rows
  phase_checkpoints: 19 rows
  pipeline_runs: 1 rows
  quality_summary_runs: 4 rows
  query_executions: 2 rows
  query_library: 8 rows
  relationships: 0 rows
  semantic_annotations: 31 rows
  slice_definitions: 4 rows
  slice_time_matrix_entries: 33 rows
  slicing_analysis_runs: 1 rows
  sources: 1 rows
  statistical_profiles: 31 rows
  statistical_quality_metrics: 23 rows
  step_results: 23 rows
  table_entities: 1 rows
  tables: 17 rows
  temporal_column_profiles: 3 rows
  temporal_drift_analyses: 165 rows
  temporal_slice_analyses: 196 rows
  temporal_slice_runs: 14 rows
  temporal_table_summaries: 1 rows
  temporal_topology_analyses: 0 rows
  type_candidates: 89 rows
  type_decisions: 81 rows
  validation_results: 4 rows
  validation_runs: 1 rows

In [ ]:
# Query all DuckDB tables (data)
import duckdb

duckdb_path = output_dir / "data.duckdb"
duck_conn = duckdb.connect(str(duckdb_path), read_only=True)

print("=== DuckDB Tables (Data) ===")
duck_tables = duck_conn.execute("SHOW TABLES").fetchall()
for t in duck_tables:
    table_name = t[0]
    count = duck_conn.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0]
    print(f"  {table_name}: {count} rows")

duck_conn.close()

# Lineage Analysis: semantic.business_meaning Actions

Tracing the 10 affected columns through the pipeline stages.

In [26]:
# Setup: Connect to both databases
import sqlite3
from pathlib import Path

import pandas as pd

output_dir = Path("./pipeline_output")
sqlite_path = output_dir / "metadata.db"
conn = sqlite3.connect(sqlite_path)


# Helper to run queries as DataFrames
def sql(query):
    return pd.read_sql_query(query, conn)

## Step 1: Sources and Tables (Base)

In [ ]:
# Get sources and tables
print("=== SOURCES ===")
display(sql("SELECT * FROM sources"))

print("\n=== TABLES ===")
display(sql("SELECT table_id, table_name, row_count FROM tables"))

In [ ]:
# Get columns for kontobuchungen table
print("=== COLUMNS (kontobuchungen) ===")
display(
    sql("""
    SELECT c.column_id, c.column_name, c.ordinal_position
    FROM columns c
    JOIN tables t ON c.table_id = t.table_id
    WHERE t.table_name = 'kontobuchungen'
    ORDER BY c.ordinal_position
""")
)

## Step 2: Type Decisions (from Typing Phase)

In [ ]:
# Type decisions - what types were resolved for each column
print("=== TYPE DECISIONS (kontobuchungen) ===")
display(
    sql("""
    SELECT c.column_name, td.resolved_type, td.confidence, td.decision_source
    FROM type_decisions td
    JOIN columns c ON td.column_id = c.column_id
    JOIN tables t ON c.table_id = t.table_id
    WHERE t.table_name = 'kontobuchungen'
""")
)

## Step 3: Statistical Profiles (from Statistics Phase)

In [ ]:
# Statistical profiles - used by semantic phase LLM for context
print("=== STATISTICAL PROFILES (kontobuchungen) ===")
display(
    sql("""
    SELECT c.column_name, sp.total_count, sp.null_count, sp.distinct_count,
           sp.null_ratio, sp.cardinality_ratio
    FROM statistical_profiles sp
    JOIN columns c ON sp.column_id = c.column_id
    JOIN tables t ON c.table_id = t.table_id
    WHERE t.table_name = 'kontobuchungen'
""")
)

## Step 4: Semantic Annotations (from Semantic Phase - LLM)

This is the **direct input** to the BusinessMeaningDetector.

In [104]:
# Semantic annotations - THE KEY INPUT to business_meaning entropy
# These fields directly feed into the detector:
# - business_description, business_name, entity_type, confidence, business_concept
print("=== SEMANTIC ANNOTATIONS (kontobuchungen) ===")
display(
    sql("""
    SELECT
        c.column_name,
        sa.semantic_role,
        sa.entity_type,
        sa.business_name,
        sa.business_description,
        sa.business_concept,
        sa.confidence,
        sa.annotation_source
    FROM semantic_annotations sa
    JOIN columns c ON sa.column_id = c.column_id
    JOIN tables t ON c.table_id = t.table_id
    WHERE t.table_name = 'kontobuchungen'
""")
)

=== SEMANTIC ANNOTATIONS (kontobuchungen) ===

ProgrammingError: Cannot operate on a closed database.

## Step 5: Entropy Objects (from Entropy Phase)

The `BusinessMeaningDetector` produces these scores from semantic annotations.

In [ ]:
# Entropy objects for semantic.business_meaning dimension
print("=== ENTROPY OBJECTS (semantic.business_meaning) ===")
display(
    sql("""
    SELECT
        eo.target,
        eo.score,
        eo.confidence,
        eo.evidence,
        eo.resolution_options
    FROM entropy_objects eo
    WHERE eo.dimension = 'business_meaning'
    AND eo.layer = 'semantic'
    ORDER BY eo.score DESC
""")
)

In [ ]:
# Parse the evidence JSON to see the score breakdown

df = sql("""
    SELECT eo.target, eo.score, eo.evidence
    FROM entropy_objects eo
    WHERE eo.dimension = 'business_meaning' AND eo.layer = 'semantic'
    ORDER BY eo.score DESC
""")

print("=== SCORE BREAKDOWN (from evidence JSON) ===")
for _, row in df.iterrows():
    evidence = json.loads(row["evidence"]) if row["evidence"] else []
    if evidence and len(evidence) > 0:
        ev = evidence[0]
        raw = ev.get("raw_metrics", {})
        comp = ev.get("score_components", {})
        print(f"\n{row['target']} (score: {row['score']:.3f})")
        print(f"  has_description: {raw.get('has_description')}")
        print(f"  has_business_name: {raw.get('has_business_name')}")
        print(f"  has_entity_type: {raw.get('has_entity_type')}")
        print(f"  semantic_confidence: {raw.get('semantic_confidence')}")
        print(f"  has_business_concept: {raw.get('has_business_concept')}")
        print(
            f"  → base_score: {comp.get('base_score')}, conf_factor: {comp.get('confidence_factor')}, ontology_bonus: {comp.get('ontology_bonus')}"
        )

## Step 6: Entropy Interpretations (from Interpretation Phase - LLM)

The LLM generates human-readable Actions from the entropy scores.

In [27]:
# Entropy interpretations - LLM-generated actions
print("=== ENTROPY INTERPRETATIONS (kontobuchungen) ===")
display(
    sql("""
    SELECT
        ei.table_name,
        ei.column_name,
        ei.composite_score,
        ei.readiness,
        ei.explanation,
        ei.resolution_actions_json
    FROM entropy_interpretations ei
    WHERE ei.table_name = 'kontobuchungen'
""")
)

=== ENTROPY INTERPRETATIONS (kontobuchungen) ===

,table_name,column_name,composite_score,readiness,explanation,resolution_actions_json
0,kontobuchungen,NaN,0.000000,investigate,The kontobuchungen table exhibits a critical d...,"[{""action"": ""review"", ""description"": ""Immediat..."
1,kontobuchungen,Belegdatum der Buchung,0.045000,ready,This DATE column has excellent overall data qu...,"[{""action"": ""add_timezone_declaration"", ""descr..."
2,kontobuchungen,WaehungsKZ Eingegebener Umsatz,0.060000,ready,This currency code column is in excellent cond...,"[{""action"": ""add_column_alias"", ""description"":..."
3,kontobuchungen,Eingegebener Umsatz,0.168774,ready,This transaction amount column has moderate un...,"[{""action"": ""add_unit_declaration"", ""descripti..."
4,kontobuchungen,Kontonummer des Gegenkontos,0.210000,ready,This offsetting account number column shows co...,"[{""action"": ""investigate_outlier_pattern"", ""de..."
5,kontobuchungen,Buchungstext,0.260390,ready,This transaction description text field has mo...,"[{""action"": ""document_null_meaning"", ""descript..."
6,kontobuchungen,Folgebuchungsatzzaehler,0.130985,ready,This follow-up posting counter has low-moderat...,"[{""action"": ""document_null_meaning"", ""descript..."
7,kontobuchungen,Rolle desw Kontos im Buchungssatz,0.074490,ready,This debit/credit role indicator has very low ...,"[{""action"": ""document_null_handling"", ""descrip..."
8,kontobuchungen,Generalumkehr (GU),0.077650,ready,This reversal flag has very low uncertainty (0...,"[{""action"": ""document_null_meaning"", ""descript..."
9,kontobuchungen,Buchungssatznummer,0.080158,ready,This posting line number has very low uncertai...,"[{""action"": ""validate_sequence_logic"", ""descri..."
10,kontobuchungen,Belegidentifikator,0.074490,ready,This document identifier has very low uncertai...,"[{""action"": ""document_null_meaning"", ""descript..."
11,kontobuchungen,Berichtigungs_Umsatzsteuerschlüssel,0.301185,investigate,This VAT adjustment tax code has significant u...,"[{""action"": ""investigate_null_ratio"", ""descrip..."
12,kontobuchungen,ID des Rechnungslegungsbereichs,0.180292,ready,This accounting area identifier has excellent ...,"[{""action"": ""investigate_outlier_pattern"", ""de..."
13,kontobuchungen,Eingegebenr Umsatz SollHaben Kennzeichen,0.060000,ready,This debit/credit flag column has excellent da...,"[{""action"": ""add_value_set_documentation"", ""de..."
14,kontobuchungen,Kontobewegung Steuersatz,0.210000,ready,This tax rate column has a composite score of ...,"[{""action"": ""add_unit_declaration"", ""descripti..."
15,kontobuchungen,Umsatz Soll,0.300000,investigate,This debit amount column has a composite score...,"[{""action"": ""add_unit_declaration"", ""descripti..."
16,kontobuchungen,Bearbeitungsstatus,0.172160,ready,This processing status code column has a compo...,"[{""action"": ""document_null_meaning"", ""descript..."
17,kontobuchungen,Kost1Kostenstelle,0.176829,ready,This cost center column has a composite score ...,"[{""action"": ""document_null_meaning"", ""descript..."
18,kontobuchungen,Kontonummer des Kontos,0.210000,ready,This general ledger account number column has ...,"[{""action"": ""add_reference_documentation"", ""de..."
19,kontobuchungen,Leistungsdatum,0.195000,ready,This service/delivery date column has a compos...,"[{""action"": ""investigate_null_cause"", ""descrip..."
20,kontobuchungen,Stapelidentifikator,0.074490,ready,This batch identifier column has an excellent ...,"[{""action"": ""document_null_meaning"", ""descript..."
21,kontobuchungen,Herkunftskennzeichen,0.074490,ready,This source system identifier column has an ex...,"[{""action"": ""add_value_set_documentation"", ""de..."
22,kontobuchungen,Umsatz Haben,0.300000,investigate,This credit amount column has moderate uncerta...,"[{""action"": ""add_unit_declaration"", ""descripti..."
23,kontobuchungen,Kontobewegungstyp,0.117579,ready,This transaction type classification column is...,"[{""action"": ""document_null_meaning"", ""descript..."
24,kontobuchungen,EU Steuersatz,0.076545,ready,This EU tax rate column is in excellent condit...,"[{""action"": ""add_unit_declaration"", ""descripti..."
25,kontobuchungen,Umrechnungskurs,0.168774,ready,This currency conversion rate column has low-m...,"[{""action"": ""add_unit_declaration"", ""descripti..."
26,kontobuchungen,Wirtschaftsjahres Monat,0.074490,ready,This fiscal year month column is in excellent ...,"[{""action"": ""document_null_meaning"", ""descript..."
27,kontobuchungen,Stapelnummer,0.060000,ready,This batch identifier column is in excellent c...,"[{""action"": ""add_business_glossary"", ""descript..."
28,kontobuchungen,Belegfeld 2,0.210000,ready,This supplementary document field has moderate...,"[{""action"": ""document_null_meaning"", ""descript..."
29,kontobuchungen,Belegnummer,0.106669,ready,This document number column has low uncertaint...,"[{""action"": ""document_null_meaning"", ""descript..."
30,kontobuchungen,Faelligkeitsdatum der Buchung,0.195000,ready,This payment due date column has moderate unce...,"[{""action"": ""document_null_meaning"", ""descript..."
31,kontobuchungen,Kennung EB-Buchung,0.224490,ready,This opening balance indicator flag has modera...,"[{""action"": ""recalibrate_outlier_detection"", ""..."

In [ ]:
# Parse resolution actions for the affected columns
affected_columns = [
    "ID des Rechnungslegungsbereichs",
    "Kontonummer des Kontos",
    "Belegdatum der Buchung",
    "Belegfeld 2",
]

print("=== RESOLUTION ACTIONS (from LLM interpretations) ===")
for col in affected_columns:
    result = sql(f"""
        SELECT resolution_actions_json
        FROM entropy_interpretations
        WHERE column_name = '{col}'
    """)
    if not result.empty:
        actions = (
            json.loads(result.iloc[0]["resolution_actions_json"])
            if result.iloc[0]["resolution_actions_json"]
            else []
        )
        print(f"\n{col}:")
        for action in actions:
            print(f"  [{action.get('priority', '?').upper()}] {action.get('action', '?')}")
            print(f"    {action.get('description', '')[:100]}...")
            print(
                f"    effort: {action.get('effort', '?')}, impact: {action.get('expected_impact', '')[:60]}..."
            )

## Step 7: Contract Evaluation

How semantic.business_meaning contributes to contract violations.

In [28]:
# Calculate the average business_meaning score across all columns
# This is what the contract evaluates against the threshold (0.1 for regulatory_reporting)

scores_df = sql("""
    SELECT eo.score
    FROM entropy_objects eo
    WHERE eo.dimension = 'business_meaning' AND eo.layer = 'semantic'
""")

avg_score = scores_df["score"].mean()
threshold = 0.1  # regulatory_reporting threshold for semantic.business_meaning

print("=== SEMANTIC.BUSINESS_MEANING CONTRACT CHECK ===")
print(f"Average score: {avg_score:.3f}")
print(f"Threshold: {threshold}")
print(f"Status: {'FAIL' if avg_score > threshold else 'PASS'}")
print(f"Excess: {avg_score - threshold:.3f}" if avg_score > threshold else "")

=== SEMANTIC.BUSINESS_MEANING CONTRACT CHECK ===
Average score: 0.200
Threshold: 0.1
Status: FAIL
Excess: 0.100

## Summary: Complete Lineage

```
Statistics Phase          Semantic Phase (LLM)         Entropy Phase              Interpretation (LLM)
     │                          │                           │                            │
statistical_profiles  →   semantic_annotations   →   entropy_objects    →    entropy_interpretations
(null_ratio, etc.)        (business_description,     (score, evidence,        (resolution_actions_json)
                           business_name,             resolution_options)
                           entity_type,
                           confidence,
                           business_concept)
                                    │
                                    ▼
                         BusinessMeaningDetector
                         Score = (base * conf_factor) - ontology_bonus
```

# Lineage Analysis: Other Entropy Dimensions

Now tracing: semantic.units, semantic.temporal, semantic.dimensional, computational.derived_values, structural.types, structural.relations

In [ ]:
# Re-open connection for remaining analysis
conn = sqlite3.connect(sqlite_path)

## semantic.units Lineage

**Detector:** `UnitEntropyDetector`
**Input:** typing (detected_unit, unit_confidence) + semantic (semantic_role)
**Logic:** Only measures columns with semantic_role='measure'. Score based on unit presence/confidence.

In [36]:
# semantic.units: Input from type_decisions (detected_unit) + semantic_annotations (semantic_role)
print("=== INPUT: Type Decisions with Units ===")
display(
    sql("""
    SELECT td.* -- c.column_name, resolved_type, decision_reason -- , detected_unit, unit_confidence
    FROM type_decisions td
    JOIN columns c ON td.column_id = c.column_id
    JOIN tables t ON c.table_id = t.table_id
    WHERE t.table_name = 'kontobuchungen'
    -- AND td.detected_unit IS NOT NULL
""")
)

print("\n=== INPUT: Semantic Role = 'measure' (only these get unit entropy) ===")
display(
    sql("""
    SELECT c.column_name, sa.semantic_role, sa.entity_type
    FROM semantic_annotations sa
    JOIN columns c ON sa.column_id = c.column_id
    JOIN tables t ON c.table_id = t.table_id
    WHERE t.table_name = 'kontobuchungen'
    AND sa.semantic_role = 'measure'
""")
)

=== INPUT: Type Decisions with Units ===

,decision_id,column_id,decided_type,decision_source,decided_at,decided_by,previous_type,decision_reason
0,f00e0037-5bab-430f-9ef9-26e6dee1c5cb,07c8b3a2-84b6-41a9-829c-e6018cf05a5a,BIGINT,automatic,2026-02-08 13:15:56.593358,None,None,Best candidate with confidence 1.00 (pattern: ...
1,f79a80ab-952b-470f-88b3-db527679faed,651ac245-a2b9-400f-9011-a0ecefdf64bd,BIGINT,automatic,2026-02-08 13:15:56.593449,None,None,Best candidate with confidence 1.00 (pattern: ...
2,2cfc36bd-1da6-4b28-8db3-2d85bd2643c0,318bbe57-42b8-4345-a117-d472a1a1d9bc,DATE,automatic,2026-02-08 13:15:56.593484,None,None,Best candidate with confidence 1.00 (pattern: ...
3,8eb37192-a420-4d68-aaa7-5da1e7d9e0fc,b77592d5-841d-4f3e-9657-5f5c0de823be,BIGINT,automatic,2026-02-08 13:15:56.593508,None,None,Best candidate with confidence 1.00 (pattern: ...
4,a04da19b-b3fe-46ad-a045-ec00c997ea04,a249cfc2-6d93-4262-921f-d253acd4496c,BIGINT,automatic,2026-02-08 13:15:56.593528,None,None,Best candidate with confidence 1.00 (pattern: ...
...,...,...,...,...,...,...,...,...
76,56bc5aed-5a6f-480e-b871-e942b6dba19d,df7aeb03-17e2-4572-b87f-abb0977b86d3,BIGINT,automatic,2026-02-08 13:15:56.594118,None,None,Best candidate with confidence 1.00 (pattern: ...
77,60fdb57c-a53f-4ee0-9f35-e02f598cd4ef,8c3a2023-858c-49ef-8f35-7ddc15b3c202,BIGINT,automatic,2026-02-08 13:15:56.594137,None,None,Best candidate with confidence 1.00 (pattern: ...
78,c8a88583-345b-4ebb-a554-9e35dc241f20,d4a2b54c-59ac-42db-ab52-9c332619f8e6,DATE,automatic,2026-02-08 13:15:56.594257,None,None,Best candidate with confidence 1.00 (pattern: ...
79,e2f0a7cc-3226-45cf-ace2-f03c9e9508c9,3d1dd9a9-02a8-4cde-baab-ac3770b7119c,DATE,automatic,2026-02-08 13:15:56.594292,None,None,Best candidate with confidence 1.00 (pattern: ...
80,b2f7fe10-8263-4506-85e9-9ee969bda522,73831b69-6f0b-45c0-a6b3-fda581812be8,BIGINT,automatic,2026-02-08 13:15:56.594309,None,None,Best candidate with confidence 1.00 (pattern: ...

=== INPUT: Semantic Role = 'measure' (only these get unit entropy) ===

           column_name semantic_role     entity_type
0          Umsatz Soll       measure    debit_amount
1         Umsatz Haben       measure   credit_amount
2  Eingegebener Umsatz       measure  entered_amount
3      Umrechnungskurs       measure   exchange_rate

In [37]:
# semantic.units: Entropy objects
print("=== ENTROPY OBJECTS (semantic.units) ===")
df_units = sql("""
    SELECT eo.target, eo.score, eo.evidence
    FROM entropy_objects eo
    WHERE eo.dimension = 'units' AND eo.layer = 'semantic'
    ORDER BY eo.score DESC
""")
display(df_units)

# Parse evidence
print("\n=== EVIDENCE BREAKDOWN ===")
for _, row in df_units.iterrows():
    evidence = json.loads(row["evidence"]) if row["evidence"] else []
    if evidence:
        ev = evidence[0]
        print(f"{row['target']} (score: {row['score']:.3f})")
        print(f"  detected_unit: {ev.get('detected_unit')}")
        print(f"  unit_confidence: {ev.get('unit_confidence')}")
        print(f"  unit_status: {ev.get('unit_status')}")

=== ENTROPY OBJECTS (semantic.units) ===

,target,score,evidence
0,column:kontobuchungen.Umsatz Soll,0.8,"[{""detected_unit"": null, ""unit_confidence"": 0...."
1,column:kontobuchungen.Umsatz Haben,0.8,"[{""detected_unit"": null, ""unit_confidence"": 0...."
2,column:kontobuchungen.Eingegebener Umsatz,0.8,"[{""detected_unit"": null, ""unit_confidence"": 0...."
3,column:kontobuchungen.Umrechnungskurs,0.8,"[{""detected_unit"": null, ""unit_confidence"": 0...."

=== EVIDENCE BREAKDOWN ===
column:kontobuchungen.Umsatz Soll (score: 0.800)
  detected_unit: None
  unit_confidence: 0.0
  unit_status: missing
column:kontobuchungen.Umsatz Haben (score: 0.800)
  detected_unit: None
  unit_confidence: 0.0
  unit_status: missing
column:kontobuchungen.Eingegebener Umsatz (score: 0.800)
  detected_unit: None
  unit_confidence: 0.0
  unit_status: missing
column:kontobuchungen.Umrechnungskurs (score: 0.800)
  detected_unit: None
  unit_confidence: 0.0
  unit_status: missing

## semantic.temporal Lineage

**Detector:** `TemporalEntropyDetector`
**Input:** typing (data_type) + semantic (semantic_role)
**Logic:** Checks alignment between date/time type and 'timestamp' semantic role.

In [41]:
# semantic.temporal: Input from type_decisions + semantic_annotations
print("=== INPUT: Date/Time Columns (type contains DATE/TIME/TIMESTAMP) ===")
display(
    sql("""
    SELECT c.column_name, resolved_type, sa.semantic_role
    FROM type_decisions td
    JOIN columns c ON td.column_id = c.column_id
    JOIN tables t ON c.table_id = t.table_id
    LEFT JOIN semantic_annotations sa ON c.column_id = sa.column_id
    WHERE t.table_name = 'kontobuchungen'
    AND (resolved_type LIKE '%DATE%' OR resolved_type LIKE '%TIME%'
         OR resolved_type LIKE '%TIMESTAMP%' OR sa.semantic_role = 'timestamp')
""")
)

=== INPUT: Date/Time Columns (type contains DATE/TIME/TIMESTAMP) ===

                     column_name resolved_type semantic_role
0         Belegdatum der Buchung          DATE     timestamp
1                 Leistungsdatum          DATE     timestamp
2  Faelligkeitsdatum der Buchung          DATE     timestamp

In [42]:
# semantic.temporal: Entropy objects
print("=== ENTROPY OBJECTS (semantic.temporal) ===")
df_temporal = sql("""
    SELECT eo.target, eo.score, eo.evidence
    FROM entropy_objects eo
    WHERE eo.dimension = 'temporal' AND eo.layer = 'semantic'
    ORDER BY eo.score DESC
""")
display(df_temporal)

# Parse evidence
print("\n=== EVIDENCE BREAKDOWN ===")
for _, row in df_temporal.iterrows():
    evidence = json.loads(row["evidence"]) if row["evidence"] else []
    if evidence:
        ev = evidence[0]
        print(f"{row['target']} (score: {row['score']:.3f})")
        print(f"  data_type: {ev.get('data_type')}")
        print(f"  semantic_role: {ev.get('semantic_role')}")
        print(f"  is_datetime_type: {ev.get('is_datetime_type')}")
        print(f"  is_marked_timestamp: {ev.get('is_marked_timestamp')}")
        print(f"  temporal_status: {ev.get('temporal_status')}")

=== ENTROPY OBJECTS (semantic.temporal) ===

,target,score,evidence
0,column:kontobuchungen.Belegdatum der Buchung,0.1,"[{""data_type"": ""DATE"", ""semantic_role"": ""times..."
1,column:kontobuchungen.Leistungsdatum,0.1,"[{""data_type"": ""DATE"", ""semantic_role"": ""times..."
2,column:kontobuchungen.Faelligkeitsdatum der Bu...,0.1,"[{""data_type"": ""DATE"", ""semantic_role"": ""times..."

=== EVIDENCE BREAKDOWN ===
column:kontobuchungen.Belegdatum der Buchung (score: 0.100)
  data_type: DATE
  semantic_role: timestamp
  is_datetime_type: True
  is_marked_timestamp: True
  temporal_status: aligned
column:kontobuchungen.Leistungsdatum (score: 0.100)
  data_type: DATE
  semantic_role: timestamp
  is_datetime_type: True
  is_marked_timestamp: True
  temporal_status: aligned
column:kontobuchungen.Faelligkeitsdatum der Buchung (score: 0.100)
  data_type: DATE
  semantic_role: timestamp
  is_datetime_type: True
  is_marked_timestamp: True
  temporal_status: aligned

## semantic.dimensional Lineage

**Detector:** `DimensionalEntropyDetector`
**Input:** quality_summary (slice_variance with columns, slice_data, temporal_columns, temporal_drift)
**Logic:** Detects cross-column patterns: mutual exclusivity, conditional dependencies, correlated variance, temporal correlations.

In [48]:
# semantic.dimensional: Input from column_quality_reports (slice variance)
print("=== INPUT: Column Quality Reports (slice variance analysis) ===")
display(
    sql("""
    SELECT cqr.column_name, cqr.slice_column_name, cqr.overall_quality_score, cqr.slice_count,cqr.overall_quality_score, cqr.quality_grade, cqr.report_data
    FROM column_quality_reports cqr
    -- WHERE cqr.source_table_name = 'kontobuchungen'
    LIMIT 5
""")
)

print("\n=== INPUT: Slice Analysis Runs ===")
display(sql("SELECT * FROM slicing_analysis_runs LIMIT 3"))

=== INPUT: Column Quality Reports (slice variance analysis) ===

,column_name,slice_column_name,overall_quality_score,slice_count,overall_quality_score,quality_grade,report_data
0,ID des Rechnungslegungsbereichs,WaehungsKZ Eingegebener Umsatz,0.95,3,0.95,A,"{""key_findings"": [""Complete data coverage acro..."
1,Kontonummer des Kontos,WaehungsKZ Eingegebener Umsatz,0.95,3,0.95,A,"{""key_findings"": [""Full data completeness acro..."
2,Belegdatum der Buchung,WaehungsKZ Eingegebener Umsatz,0.95,3,0.95,A,"{""key_findings"": [""Complete date coverage for ..."
3,Berichtigungs_Umsatzsteuerschlüssel,WaehungsKZ Eingegebener Umsatz,0.95,3,0.95,A,"{""key_findings"": [""Full data coverage across a..."
4,Kontonummer des Gegenkontos,WaehungsKZ Eingegebener Umsatz,0.95,3,0.95,A,"{""key_findings"": [""Complete coverage for all 3..."

=== INPUT: Slice Analysis Runs ===

,run_id,table_ids,tables_analyzed,columns_considered,recommendations_count,slices_generated,started_at,completed_at,duration_seconds,status,error_message
0,deddc934-bd13-4648-abdc-483cd67e23af,"[""8509255b-e503-47a2-8817-521e33334f9e""]",1,31,4,14,2026-02-08 13:16:49.314388,2026-02-08 13:17:09.115489,19.801101,completed,None

In [ ]:
# semantic.dimensional: Entropy objects (cross-column patterns)
print("=== ENTROPY OBJECTS (semantic.dimensional) ===")
df_dim = sql("""
    SELECT eo.target, eo.sub_dimension, eo.score, eo.evidence
    FROM entropy_objects eo
    WHERE eo.dimension = 'dimensional' AND eo.layer = 'semantic'
    ORDER BY eo.score DESC
""")
display(df_dim)
df_dim["column_name"] = df_dim["target"].apply(lambda x: x.replace("column:kontobuchungen.", ""))

# Parse evidence for pattern details
print("\n=== PATTERN DETAILS ===")
for _, row in df_dim.head(5).iterrows():
    evidence = json.loads(row["evidence"]) if row["evidence"] else []
    if evidence:
        ev = evidence[0]
        print(f"\n{row['target']} ({row['sub_dimension']}, score: {row['score']:.3f})")
        if "pattern_type" in ev:
            print(f"  pattern_type: {ev.get('pattern_type')}")
            print(f"  columns: {ev.get('columns')}")
            print(f"  confidence: {ev.get('confidence')}")
            print(f"  hypothesis: {ev.get('business_rule_hypothesis', '')[:100]}...")
        elif "dimensional_entropy_score" in ev:
            des = ev["dimensional_entropy_score"]
            print(f"  total_patterns: {des.get('total_patterns')}")
            print(f"  pattern_breakdown: {des.get('pattern_breakdown')}")

=== ENTROPY OBJECTS (semantic.dimensional) ===

,target,sub_dimension,score,evidence
0,column:kontobuchungen.Rolle desw Kontos im Buc...,column_quality,0.250,"[{""source"": ""column_quality_report"", ""column_i..."
1,column:kontobuchungen.Folgebuchungsatzzaehler,column_quality,0.250,"[{""source"": ""column_quality_report"", ""column_i..."
2,column:kontobuchungen.Generalumkehr (GU),column_quality,0.240,"[{""source"": ""column_quality_report"", ""column_i..."
3,column:kontobuchungen.Stapelidentifikator,column_quality,0.220,"[{""source"": ""column_quality_report"", ""column_i..."
4,column:kontobuchungen.Belegidentifikator,column_quality,0.220,"[{""source"": ""column_quality_report"", ""column_i..."
5,column:kontobuchungen.Leistungsdatum,column_quality,0.220,"[{""source"": ""column_quality_report"", ""column_i..."
6,column:kontobuchungen.Faelligkeitsdatum der Bu...,column_quality,0.220,"[{""source"": ""column_quality_report"", ""column_i..."
7,column:kontobuchungen.Umrechnungskurs,column_quality,0.135,"[{""source"": ""column_quality_report"", ""column_i..."
8,column:kontobuchungen.Umsatz Soll,column_quality,0.115,"[{""source"": ""column_quality_report"", ""column_i..."
9,column:kontobuchungen.Umsatz Haben,column_quality,0.115,"[{""source"": ""column_quality_report"", ""column_i..."
10,column:kontobuchungen.Eingegebener Umsatz,column_quality,0.115,"[{""source"": ""column_quality_report"", ""column_i..."
11,column:kontobuchungen.Stapelnummer,column_quality,0.110,"[{""source"": ""column_quality_report"", ""column_i..."
12,column:kontobuchungen.Buchungssatznummer,column_quality,0.110,"[{""source"": ""column_quality_report"", ""column_i..."
13,column:kontobuchungen.Kost1Kostenstelle,column_quality,0.110,"[{""source"": ""column_quality_report"", ""column_i..."
14,column:kontobuchungen.Kennung EB-Buchung,column_quality,0.110,"[{""source"": ""column_quality_report"", ""column_i..."
15,column:kontobuchungen.Bearbeitungsstatus,column_quality,0.110,"[{""source"": ""column_quality_report"", ""column_i..."
16,column:kontobuchungen.Kontobewegungstyp,column_quality,0.110,"[{""source"": ""column_quality_report"", ""column_i..."
17,column:kontobuchungen.ID des Rechnungslegungsb...,column_quality,0.050,"[{""source"": ""column_quality_report"", ""column_i..."
18,column:kontobuchungen.Kontonummer des Kontos,column_quality,0.050,"[{""source"": ""column_quality_report"", ""column_i..."
19,column:kontobuchungen.Belegdatum der Buchung,column_quality,0.050,"[{""source"": ""column_quality_report"", ""column_i..."
20,column:kontobuchungen.Berichtigungs_Umsatzsteu...,column_quality,0.050,"[{""source"": ""column_quality_report"", ""column_i..."
21,column:kontobuchungen.Kontonummer des Gegenkontos,column_quality,0.050,"[{""source"": ""column_quality_report"", ""column_i..."
22,column:kontobuchungen.Buchungstext,column_quality,0.050,"[{""source"": ""column_quality_report"", ""column_i..."
23,column:kontobuchungen.Kontobewegung Steuersatz,column_quality,0.050,"[{""source"": ""column_quality_report"", ""column_i..."
24,column:kontobuchungen.EU Steuersatz,column_quality,0.050,"[{""source"": ""column_quality_report"", ""column_i..."
25,column:kontobuchungen.Belegnummer,column_quality,0.050,"[{""source"": ""column_quality_report"", ""column_i..."
26,column:kontobuchungen.Belegfeld 2,column_quality,0.050,"[{""source"": ""column_quality_report"", ""column_i..."

=== PATTERN DETAILS ===

column:kontobuchungen.Rolle desw Kontos im Buchungssatz (column_quality, score: 0.250)

column:kontobuchungen.Folgebuchungsatzzaehler (column_quality, score: 0.250)

column:kontobuchungen.Generalumkehr (GU) (column_quality, score: 0.240)

column:kontobuchungen.Stapelidentifikator (column_quality, score: 0.220)

column:kontobuchungen.Belegidentifikator (column_quality, score: 0.220)

## computational.derived_values Lineage

**Detector:** `DerivedValueDetector`
**Input:** correlation (derived_columns with formula, match_rate)
**Logic:** Measures formula match rate. Higher mismatch = higher entropy.

In [57]:
# computational.derived_values: Input from derived_columns (correlation phase)
print("=== INPUT: Derived Columns (from correlation analysis) ===")
display(
    sql("""
    SELECT c.column_name as derived_column_name, dc.derivation_type, dc.formula, dc.match_rate, dc.total_rows, dc.matching_rows -- dc.source_column_names
    FROM derived_columns dc LEFT JOIN columns c ON dc.derived_column_id = c.column_id
    -- LIMIT 10
""")
)

=== INPUT: Derived Columns (from correlation analysis) ===

,derived_column_name,derivation_type,formula,match_rate,total_rows,matching_rows
0,ID des Rechnungslegungsbereichs,product,EU Steuersatz * Berichtigungs_Umsatzsteuerschl...,0.963526,658,634
1,ID des Rechnungslegungsbereichs,product,EU Steuersatz * Belegfeld 2,1.000000,42,42
2,ID des Rechnungslegungsbereichs,product,Belegfeld 2 * Kennung EB-Buchung,1.000000,34,34
3,ID des Rechnungslegungsbereichs,product,Belegfeld 2 * Generalumkehr (GU),1.000000,34,34
4,ID des Rechnungslegungsbereichs,product,Eingegebener Umsatz * Berichtigungs_Umsatzsteu...,1.000000,658,658
...,...,...,...,...,...,...
193,Generalumkehr (GU),ratio,Kontobewegungstyp / Kontonummer des Gegenkontos,0.998085,3133,3127
194,Generalumkehr (GU),ratio,Rolle desw Kontos im Buchungssatz / Kontonumme...,0.995212,3133,3118
195,Generalumkehr (GU),ratio,Rolle desw Kontos im Buchungssatz / Kontonumme...,0.998085,3133,3127
196,Generalumkehr (GU),ratio,Folgebuchungsatzzaehler / Kontonummer des Kontos,0.998085,3133,3127
197,Generalumkehr (GU),ratio,Folgebuchungsatzzaehler / Kontonummer des Gege...,0.998085,3133,3127

In [58]:
# computational.derived_values: Entropy objects
print("=== ENTROPY OBJECTS (computational.derived_values) ===")
df_derived = sql("""
    SELECT eo.target, eo.score, eo.evidence
    FROM entropy_objects eo
    WHERE eo.dimension = 'derived_values' AND eo.layer = 'computational'
    ORDER BY eo.score DESC
""")
display(df_derived)

# Parse evidence
print("\n=== EVIDENCE BREAKDOWN ===")
for _, row in df_derived.head(5).iterrows():
    evidence = json.loads(row["evidence"]) if row["evidence"] else []
    if evidence:
        ev = evidence[0]
        print(f"{row['target']} (score: {row['score']:.3f})")
        print(f"  status: {ev.get('status')}")
        print(f"  formula: {ev.get('formula')}")
        print(f"  match_rate: {ev.get('match_rate')}")

=== ENTROPY OBJECTS (computational.derived_values) ===

,target,score,evidence
0,column:kontobuchungen.Buchungssatznummer,0.040217,"[{""status"": ""near_exact"", ""formula"": ""Generalu..."
1,column:kontobuchungen.Eingegebener Umsatz,0.012767,"[{""status"": ""near_exact"", ""formula"": ""Generalu..."
2,column:kontobuchungen.Umrechnungskurs,0.012767,"[{""status"": ""near_exact"", ""formula"": ""Generalu..."
3,column:kontobuchungen.EU Steuersatz,0.007022,"[{""status"": ""exact"", ""formula"": ""Generalumkehr..."
4,column:kontobuchungen.Generalumkehr (GU),0.001915,"[{""status"": ""exact"", ""formula"": ""Folgebuchungs..."
5,column:kontobuchungen.ID des Rechnungslegungsb...,0.000000,"[{""status"": ""exact"", ""formula"": ""Generalumkehr..."
6,column:kontobuchungen.Kennung EB-Buchung,0.000000,"[{""status"": ""exact"", ""formula"": ""Generalumkehr..."

=== EVIDENCE BREAKDOWN ===
column:kontobuchungen.Buchungssatznummer (score: 0.040)
  status: near_exact
  formula: Generalumkehr (GU) + Belegidentifikator
  match_rate: 0.9597829556335781
column:kontobuchungen.Eingegebener Umsatz (score: 0.013)
  status: near_exact
  formula: Generalumkehr (GU) * Belegidentifikator
  match_rate: 0.9872326843281201
column:kontobuchungen.Umrechnungskurs (score: 0.013)
  status: near_exact
  formula: Generalumkehr (GU) * Belegidentifikator
  match_rate: 0.9872326843281201
column:kontobuchungen.EU Steuersatz (score: 0.007)
  status: exact
  formula: Generalumkehr (GU) * Belegidentifikator
  match_rate: 0.992977976380466
column:kontobuchungen.Generalumkehr (GU) (score: 0.002)
  status: exact
  formula: Folgebuchungsatzzaehler / Kontonummer des Gegenkontos
  match_rate: 0.998084902649218

## structural.types Lineage

**Detector:** `TypeFidelityDetector`
**Input:** typing (parse_success_rate, data_type, failed_examples)
**Logic:** Entropy = 1.0 - parse_success_rate. Low success = high entropy.

In [ ]:
# structural.types: Input from type_candidates (typing phase)
print("=== INPUT: Type Candidates with Parse Success Rate ===")
display(
    sql("""
    SELECT DISTINCT c.column_name, tc.data_type, tc.parse_success_rate, tc.confidence, tc.confidence, tc.parse_success_rate,tc.failed_examples
    FROM type_candidates tc
    JOIN columns c ON tc.column_id = c.column_id
    JOIN tables t ON c.table_id = t.table_id
    WHERE t.table_name = 'kontobuchungen'
    ORDER BY tc.parse_success_rate ASC
""")
)

=== INPUT: Type Candidates with Parse Success Rate ===

,column_name,data_type,parse_success_rate,confidence,confidence,parse_success_rate,failed_examples
0,Buchungstext,DOUBLE,0.505000,0.505000,0.505000,0.505000,[]
1,Belegnummer,BIGINT,0.933779,0.903717,0.903717,0.933779,"[""AZ2025-1"", ""AZ2025-1"", ""202410048GS"", ""AZ202..."
2,ID des Rechnungslegungsbereichs,BOOLEAN,0.959295,0.812981,0.812981,0.959295,"[""2"", ""2"", ""2"", ""2"", ""2""]"
3,Folgebuchungsatzzaehler,BOOLEAN,0.962336,0.731168,0.731168,0.962336,"[""2"", ""2"", ""2"", ""2"", ""2""]"
4,ID des Rechnungslegungsbereichs,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
5,Kontonummer des Kontos,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
6,Belegdatum der Buchung,DATE,1.000000,1.000000,1.000000,1.000000,[]
7,Berichtigungs_Umsatzsteuerschlüssel,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
8,Kontonummer des Gegenkontos,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
9,Kontobewegung Steuersatz,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
10,EU Steuersatz,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
11,Belegfeld 2,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
12,Umsatz Soll,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
13,Umsatz Haben,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
14,Eingegebenr Umsatz SollHaben Kennzeichen,VARCHAR,1.000000,1.000000,1.000000,1.000000,[]
15,Eingegebener Umsatz,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
16,WaehungsKZ Eingegebener Umsatz,VARCHAR,1.000000,1.000000,1.000000,1.000000,[]
17,Umrechnungskurs,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
18,Basiswaehrung,VARCHAR,1.000000,1.000000,1.000000,1.000000,[]
19,Stapelnummer,VARCHAR,1.000000,1.000000,1.000000,1.000000,[]
20,Buchungssatznummer,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
21,Kost1Kostenstelle,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
22,Kost Mengenfeld,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
23,Kost Mengenfeld,BOOLEAN,1.000000,1.000000,1.000000,1.000000,[]
24,Kennung EB-Buchung,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
25,Kennung EB-Buchung,BOOLEAN,1.000000,1.000000,1.000000,1.000000,[]
26,Wirtschaftsjahres Monat,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
27,Buchungstyp,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
28,Buchungstyp,BOOLEAN,1.000000,1.000000,1.000000,1.000000,[]
29,Bearbeitungsstatus,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
30,Belegpruefungsstatus,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
31,Belegpruefungsstatus,BOOLEAN,1.000000,1.000000,1.000000,1.000000,[]
32,Kontobewegungstyp,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
33,Rolle desw Kontos im Buchungssatz,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
34,Folgebuchungsatzzaehler,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
35,Abweichende Besteuerungsart,VARCHAR,1.000000,1.000000,1.000000,1.000000,[]
36,Sachverhalt Lieferungen und Leistungen,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
37,Sachverhalt Lieferungen und Leistungen,BOOLEAN,1.000000,1.000000,1.000000,1.000000,[]
38,Funktionsergaenzung Lieferungen und Leistungen,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
39,Funktionsergaenzung Lieferungen und Leistungen,BOOLEAN,1.000000,1.000000,1.000000,1.000000,[]
40,Hauptfunktionstyp Steuerschluessel 49,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
41,Hauptfunktionstyp Steuerschluessel 49,BOOLEAN,1.000000,1.000000,1.000000,1.000000,[]
42,Hauptfunktionsnummer Steuerschluessel 49,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
43,Hauptfunktionsnummer Steuerschluessel 49,BOOLEAN,1.000000,1.000000,1.000000,1.000000,[]
44,Funktionsergaenzung Steuerschluessel 49,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
45,Funktionsergaenzung Steuerschluessel 49,BOOLEAN,1.000000,1.000000,1.000000,1.000000,[]
46,Herkunftskennzeichen,VARCHAR,1.000000,1.000000,1.000000,1.000000,[]
47,Stapelidentifikator,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
48,Belegidentifikator,BIGINT,1.000000,1.000000,1.000000,1.000000,[]
49,Leistungsdatum,DATE,1.000000,1.000000,1.000000,1.000000,[]
50,Datum Zuord. Steuerperiode,DATE,1.000000,1.000000,1.000000,1.000000,[]
51,Faelligkeitsdatum der Buchung,DATE,1.000000,1.000000,1.000000,1.000000,[]
52,Generalumkehr (GU),BIGINT,1.000000,1.000000,1.000000,1.000000,[]
53,Generalumkehr (GU),BOOLEAN,1.000000,1.000000,1.000000,1.000000,[]

In [77]:
# structural.types: Entropy objects
print("=== ENTROPY OBJECTS (structural.types) ===")
df_types = sql("""
    SELECT eo.target, eo.score, eo.evidence
    FROM entropy_objects eo
    WHERE eo.dimension = 'types' AND eo.layer = 'structural'
    ORDER BY eo.score DESC
""")
display(df_types.head(10))
df_types["column_name"] = df_types["target"].apply(
    lambda x: x.replace("column:kontobuchungen.", "")
)
# Parse evidence
print("\n=== EVIDENCE BREAKDOWN (top 5 highest entropy) ===")
for _, row in df_types.head(5).iterrows():
    evidence = json.loads(row["evidence"]) if row["evidence"] else []
    if evidence:
        ev = evidence[0]
        print(f"{row['target']} (score: {row['score']:.3f})")
        print(f"  parse_success_rate: {ev.get('parse_success_rate')}")
        print(f"  detected_type: {ev.get('detected_type')}")
        print(f"  failure_count: {ev.get('failure_count')}")

=== ENTROPY OBJECTS (structural.types) ===

,target,score,evidence
0,column:kontobuchungen.Buchungstext,0.495000,"[{""parse_success_rate"": 0.505, ""detected_type""..."
1,column:kontobuchungen.Belegnummer,0.066221,"[{""parse_success_rate"": 0.9337788578371811, ""d..."
2,column:kontobuchungen.ID des Rechnungslegungsb...,0.000000,"[{""parse_success_rate"": 1.0, ""detected_type"": ..."
3,column:kontobuchungen.Kontonummer des Kontos,0.000000,"[{""parse_success_rate"": 1.0, ""detected_type"": ..."
4,column:kontobuchungen.Belegdatum der Buchung,0.000000,"[{""parse_success_rate"": 1.0, ""detected_type"": ..."
5,column:kontobuchungen.Berichtigungs_Umsatzsteu...,0.000000,"[{""parse_success_rate"": 1.0, ""detected_type"": ..."
6,column:kontobuchungen.Kontonummer des Gegenkontos,0.000000,"[{""parse_success_rate"": 1.0, ""detected_type"": ..."
7,column:kontobuchungen.Kontobewegung Steuersatz,0.000000,"[{""parse_success_rate"": 1.0, ""detected_type"": ..."
8,column:kontobuchungen.EU Steuersatz,0.000000,"[{""parse_success_rate"": 1.0, ""detected_type"": ..."
9,column:kontobuchungen.Belegfeld 2,0.000000,"[{""parse_success_rate"": 1.0, ""detected_type"": ..."

=== EVIDENCE BREAKDOWN (top 5 highest entropy) ===
column:kontobuchungen.Buchungstext (score: 0.495)
  parse_success_rate: 0.505
  detected_type: VARCHAR
  failure_count: 0
column:kontobuchungen.Belegnummer (score: 0.066)
  parse_success_rate: 0.9337788578371811
  detected_type: BIGINT
  failure_count: 5
column:kontobuchungen.ID des Rechnungslegungsbereichs (score: 0.000)
  parse_success_rate: 1.0
  detected_type: BIGINT
  failure_count: 0
column:kontobuchungen.Kontonummer des Kontos (score: 0.000)
  parse_success_rate: 1.0
  detected_type: BIGINT
  failure_count: 0
column:kontobuchungen.Belegdatum der Buchung (score: 0.000)
  parse_success_rate: 1.0
  detected_type: DATE
  failure_count: 0

## structural.relations Lineage

**Detector:** `JoinPathDeterminismDetector`
**Input:** relationships (from semantic phase, LLM-confirmed)
**Logic:** Measures join path ambiguity. Multiple paths to SAME table = high entropy.

In [83]:
# structural.relations: Input from relationships table
print("=== INPUT: Relationships (LLM-confirmed joins) ===")
display(
    sql("""
    SELECT tf.table_name as from_table_name, tt.table_name as to_table_name, cf.column_name as from_column_name, ct.column_name as to_column_name, r.relationship_type, r.confidence, r.evidence
    FROM relationships r
            LEFT JOIN tables tf ON r.from_table_id = tf.table_id
            LEFT JOIN tables tt ON r.to_table_id = tt.table_id
            LEFT JOIN columns cf ON r.from_column_id = cf.column_id
            LEFT JOIN columns ct ON r.to_column_id = ct.column_id
""")
)

=== INPUT: Relationships (LLM-confirmed joins) ===

Empty DataFrame
Columns: [from_table_name, to_table_name, from_column_name, to_column_name, relationship_type, confidence, evidence]
Index: []

In [84]:
# structural.relations: Entropy objects
print("=== ENTROPY OBJECTS (structural.relations) ===")
df_relations = sql("""
    SELECT eo.target, eo.score, eo.evidence
    FROM entropy_objects eo
    WHERE eo.dimension = 'relations' AND eo.layer = 'structural'
    ORDER BY eo.score DESC
""")
display(df_relations.head(10))

# Parse evidence
print("\n=== EVIDENCE BREAKDOWN ===")
for _, row in df_relations.head(5).iterrows():
    evidence = json.loads(row["evidence"]) if row["evidence"] else []
    if evidence:
        ev = evidence[0]
        print(f"{row['target']} (score: {row['score']:.3f})")
        print(f"  path_status: {ev.get('path_status')}")
        print(f"  connected_tables: {ev.get('connected_tables')}")
        print(f"  ambiguous_tables: {ev.get('ambiguous_tables')}")

=== ENTROPY OBJECTS (structural.relations) ===

Empty DataFrame
Columns: [target, score, evidence]
Index: []

=== EVIDENCE BREAKDOWN ===

## value.outliers Lineage

**Detector:** `OutlierRateDetector`
**Input:** statistics/quality (iqr_outlier_ratio, iqr_outlier_count, iqr_lower_fence, iqr_upper_fence)
**Logic:** entropy = min(1.0, outlier_ratio * 10). High outlier rate = high entropy.

In [113]:
# value.outliers: Input from statistical_quality_metrics (outlier detection)
print("=== INPUT: Statistical Quality Metrics (outlier detection) ===")
display(
    sql("""
    SELECT c.column_name, sqm.benford_compliant,sqm.iqr_outlier_ratio, sqm.isolation_forest_anomaly_ratio,sqm.quality_data --  sqm.iqr_lower_fence, sqm.iqr_upper_fence, sqm.zscore_outlier_ratio
    FROM statistical_quality_metrics sqm
    JOIN columns c ON sqm.column_id = c.column_id
    JOIN tables t ON c.table_id = t.table_id
    WHERE t.table_name = 'kontobuchungen'
    ORDER BY sqm.iqr_outlier_ratio DESC
""")
)

=== INPUT: Statistical Quality Metrics (outlier detection) ===

,column_name,benford_compliant,iqr_outlier_ratio,isolation_forest_anomaly_ratio,quality_data
0,Kontonummer des Gegenkontos,0.0,0.217801,0.050122,"{""column_id"": ""5cbd1058-851d-4299-b276-20ce06d..."
1,Kontobewegung Steuersatz,0.0,0.208080,0.016707,"{""column_id"": ""a68b6e11-3baf-440b-9297-6a8860d..."
2,Kontonummer des Kontos,0.0,0.166160,0.049210,"{""column_id"": ""cf13ab15-7f7b-4f9c-8e47-ac42702..."
3,Umsatz Haben,0.0,0.135480,0.050122,"{""column_id"": ""1ac70d41-899a-48e4-b1b1-edc9afd..."
4,Umsatz Soll,0.0,0.120899,0.049210,"{""column_id"": ""c21f68cc-83fb-44f5-a33a-5912eab..."
5,Kennung EB-Buchung,0.0,0.111714,0.000000,"{""column_id"": ""3fb89560-b932-4bc6-b158-2c1bc62..."
6,ID des Rechnungslegungsbereichs,0.0,0.080194,0.040705,"{""column_id"": ""a409bf4a-79bf-4132-b7d7-c6e0a5e..."
7,Bearbeitungsstatus,0.0,0.065113,0.000000,"{""column_id"": ""c59af347-b348-4ec1-8324-fe056d7..."
8,Berichtigungs_Umsatzsteuerschlüssel,0.0,0.060790,0.045593,"{""column_id"": ""a354b931-1afe-42d0-8e34-29f6f38..."
9,Folgebuchungsatzzaehler,0.0,0.037664,0.037664,"{""column_id"": ""6ab63776-ff55-4e6f-a382-b5186f2..."
10,Kontobewegungstyp,0.0,0.028726,0.028726,"{""column_id"": ""1dbd9b57-13e4-4a9c-aa05-f734d5d..."
11,Eingegebener Umsatz,NaN,0.011239,0.011239,"{""column_id"": ""43dad524-f5f4-45c6-8e8a-405eb0b..."
12,Umrechnungskurs,NaN,0.011239,0.011239,"{""column_id"": ""2a046220-453e-4dbf-9bdd-e81e714..."
13,EU Steuersatz,NaN,0.010328,0.010328,"{""column_id"": ""241aa636-facc-4bd1-a947-5ef05cd..."
14,Buchungssatznummer,0.0,0.009417,0.047995,"{""column_id"": ""7b11d838-c23b-4b42-9125-19a60f0..."
15,Belegnummer,0.0,0.006831,0.050098,"{""column_id"": ""3c511682-1c78-4306-b7bf-cf33f6c..."
16,Generalumkehr (GU),NaN,0.001915,0.001915,"{""column_id"": ""73831b69-6f0b-45c0-a6b3-fda5818..."
17,Belegfeld 2,NaN,0.000000,0.000000,"{""column_id"": ""3915a4a2-9068-4a0d-9765-d9c3cf5..."
18,Kost1Kostenstelle,0.0,0.000000,0.033831,"{""column_id"": ""cbe4690f-bd4d-410d-93a2-2cd468b..."
19,Wirtschaftsjahres Monat,0.0,0.000000,0.000000,"{""column_id"": ""2e6b6305-c474-456c-ad88-95fd5e8..."
20,Rolle desw Kontos im Buchungssatz,0.0,0.000000,0.000000,"{""column_id"": ""70090746-a294-4336-a6b4-427b307..."
21,Stapelidentifikator,0.0,0.000000,0.049793,"{""column_id"": ""df7aeb03-17e2-4572-b87f-abb0977..."
22,Belegidentifikator,0.0,0.000000,0.049793,"{""column_id"": ""8c3a2023-858c-49ef-8f35-7ddc15b..."

In [114]:
# value.outliers: Entropy objects
print("=== ENTROPY OBJECTS (value.outliers) ===")
df_outliers = sql("""
    SELECT eo.target, eo.score, eo.evidence
    FROM entropy_objects eo
    WHERE eo.dimension = 'outliers' AND eo.layer = 'value'
    ORDER BY eo.score DESC
""")
display(df_outliers)

# Parse evidence
print("\n=== EVIDENCE BREAKDOWN ===")
for _, row in df_outliers.head(10).iterrows():
    evidence = json.loads(row["evidence"]) if row["evidence"] else []
    if evidence:
        ev = evidence[0]
        print(f"{row['target']} (score: {row['score']:.3f})")
        print(f"  outlier_ratio: {ev.get('outlier_ratio')}")
        print(f"  outlier_count: {ev.get('outlier_count')}")
        print(f"  outlier_impact: {ev.get('outlier_impact')}")
        print(f"  iqr_fences: [{ev.get('iqr_lower_fence')}, {ev.get('iqr_upper_fence')}]")

=== ENTROPY OBJECTS (value.outliers) ===

,target,score,evidence
0,column:kontobuchungen.Kontonummer des Kontos,1.000000,"[{""outlier_ratio"": 0.16616038882138517, ""outli..."
1,column:kontobuchungen.Kontonummer des Gegenkontos,1.000000,"[{""outlier_ratio"": 0.2178007290400972, ""outlie..."
2,column:kontobuchungen.Kontobewegung Steuersatz,1.000000,"[{""outlier_ratio"": 0.2080801944106926, ""outlie..."
3,column:kontobuchungen.Umsatz Soll,1.000000,"[{""outlier_ratio"": 0.12089914945321993, ""outli..."
4,column:kontobuchungen.Umsatz Haben,1.000000,"[{""outlier_ratio"": 0.13547995139732685, ""outli..."
5,column:kontobuchungen.Kennung EB-Buchung,1.000000,"[{""outlier_ratio"": 0.1117140121289499, ""outlie..."
6,column:kontobuchungen.ID des Rechnungslegungsb...,0.801944,"[{""outlier_ratio"": 0.08019441069258809, ""outli..."
7,column:kontobuchungen.Bearbeitungsstatus,0.651133,"[{""outlier_ratio"": 0.06511330992658794, ""outli..."
8,column:kontobuchungen.Berichtigungs_Umsatzsteu...,0.607903,"[{""outlier_ratio"": 0.060790273556231005, ""outl..."
9,column:kontobuchungen.Folgebuchungsatzzaehler,0.376636,"[{""outlier_ratio"": 0.03766358123204596, ""outli..."
10,column:kontobuchungen.Kontobewegungstyp,0.287265,"[{""outlier_ratio"": 0.02872646026172997, ""outli..."
11,column:kontobuchungen.Eingegebener Umsatz,0.112394,"[{""outlier_ratio"": 0.011239368165249088, ""outl..."
12,column:kontobuchungen.Umrechnungskurs,0.112394,"[{""outlier_ratio"": 0.011239368165249088, ""outl..."
13,column:kontobuchungen.EU Steuersatz,0.103281,"[{""outlier_ratio"": 0.010328068043742407, ""outl..."
14,column:kontobuchungen.Buchungssatznummer,0.094168,"[{""outlier_ratio"": 0.009416767922235723, ""outl..."
15,column:kontobuchungen.Belegnummer,0.068315,"[{""outlier_ratio"": 0.0068314899154196486, ""out..."
16,column:kontobuchungen.Generalumkehr (GU),0.019151,"[{""outlier_ratio"": 0.001915097350781998, ""outl..."
17,column:kontobuchungen.Belegdatum der Buchung,0.000000,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o..."
18,column:kontobuchungen.Buchungstext,0.000000,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o..."
19,column:kontobuchungen.Belegfeld 2,0.000000,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o..."
20,column:kontobuchungen.Eingegebenr Umsatz SollH...,0.000000,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o..."
21,column:kontobuchungen.WaehungsKZ Eingegebener ...,0.000000,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o..."
22,column:kontobuchungen.Stapelnummer,0.000000,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o..."
23,column:kontobuchungen.Kost1Kostenstelle,0.000000,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o..."
24,column:kontobuchungen.Wirtschaftsjahres Monat,0.000000,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o..."
25,column:kontobuchungen.Rolle desw Kontos im Buc...,0.000000,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o..."
26,column:kontobuchungen.Herkunftskennzeichen,0.000000,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o..."
27,column:kontobuchungen.Stapelidentifikator,0.000000,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o..."
28,column:kontobuchungen.Belegidentifikator,0.000000,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o..."
29,column:kontobuchungen.Leistungsdatum,0.000000,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o..."
30,column:kontobuchungen.Faelligkeitsdatum der Bu...,0.000000,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o..."

=== EVIDENCE BREAKDOWN ===
column:kontobuchungen.Kontonummer des Kontos (score: 1.000)
  outlier_ratio: 0.16616038882138517
  outlier_count: 0
  outlier_impact: critical
  iqr_fences: [None, None]
column:kontobuchungen.Kontonummer des Gegenkontos (score: 1.000)
  outlier_ratio: 0.2178007290400972
  outlier_count: 0
  outlier_impact: critical
  iqr_fences: [None, None]
column:kontobuchungen.Kontobewegung Steuersatz (score: 1.000)
  outlier_ratio: 0.2080801944106926
  outlier_count: 0
  outlier_impact: critical
  iqr_fences: [None, None]
column:kontobuchungen.Umsatz Soll (score: 1.000)
  outlier_ratio: 0.12089914945321993
  outlier_count: 0
  outlier_impact: critical
  iqr_fences: [None, None]
column:kontobuchungen.Umsatz Haben (score: 1.000)
  outlier_ratio: 0.13547995139732685
  outlier_count: 0
  outlier_impact: critical
  iqr_fences: [None, None]
column:kontobuchungen.Kennung EB-Buchung (score: 1.000)
  outlier_ratio: 0.1117140121289499
  outlier_count: 0
  outlier_impact: critical
  iqr_fences: [None, None]
column:kontobuchungen.ID des Rechnungslegungsbereichs (score: 0.802)
  outlier_ratio: 0.08019441069258809
  outlier_count: 0
  outlier_impact: significant
  iqr_fences: [None, None]
column:kontobuchungen.Bearbeitungsstatus (score: 0.651)
  outlier_ratio: 0.06511330992658794
  outlier_count: 0
  outlier_impact: significant
  iqr_fences: [None, None]
column:kontobuchungen.Berichtigungs_Umsatzsteuerschlüssel (score: 0.608)
  outlier_ratio: 0.060790273556231005
  outlier_count: 0
  outlier_impact: significant
  iqr_fences: [None, None]
column:kontobuchungen.Folgebuchungsatzzaehler (score: 0.377)
  outlier_ratio: 0.03766358123204596
  outlier_count: 0
  outlier_impact: moderate
  iqr_fences: [None, None]

## Summary: All Entropy Dimensions

| Dimension | Detector | Input Source | Key Metric |
|-----------|----------|--------------|------------|
| semantic.business_meaning | BusinessMeaningDetector | semantic_annotations | has_description, business_name, entity_type, confidence |
| semantic.units | UnitEntropyDetector | type_decisions + semantic_annotations | detected_unit, unit_confidence (measures only) |
| semantic.temporal | TemporalEntropyDetector | type_decisions + semantic_annotations | data_type vs semantic_role alignment |
| semantic.dimensional | DimensionalEntropyDetector | quality_summary (slice_variance) | cross-column pattern detection |
| computational.derived_values | DerivedValueDetector | derived_columns (correlation) | formula match_rate |
| structural.types | TypeFidelityDetector | type_candidates | parse_success_rate |
| structural.relations | JoinPathDeterminismDetector | relationships | join path ambiguity |
| value.outliers | OutlierRateDetector | statistical_quality_metrics | iqr_outlier_ratio * 10 |

# Complete Column Lineage View

A single joined query showing all pipeline stages per column.

In [115]:
# Re-open connection
conn = sqlite3.connect(sqlite_path)

# Complete column lineage query - joins all pipeline stages
lineage_query = """
WITH base AS (
    -- Base: columns from kontobuchungen
    SELECT
        c.column_id,
        c.column_name,
        t.table_name
    FROM columns c
    JOIN tables t ON c.table_id = t.table_id
    WHERE t.table_name = 'kontobuchungen' and t.layer='typed'
),

-- Stage 1: Type Decisions
typing AS (
    SELECT
        td.column_id,
        td.decided_type AS resolved_type,
        td.decision_source AS type_source,
        td.decision_reason AS type_reason
    FROM type_decisions td
),

-- Stage 1b: Type Candidates (for parse_success_rate)
type_candidates_agg AS (
    SELECT
        td.column_id,
        tc.parse_success_rate
    FROM type_decisions td
    JOIN type_candidates tc ON td.column_id = tc.column_id
        AND td.decided_type = tc.data_type
),

-- Stage 2: Statistical Profiles
statistics AS (
    SELECT
        sp.column_id,
        sp.total_count,
        sp.null_count,
        sp.distinct_count,
        sp.null_ratio,
        sp.cardinality_ratio
    FROM statistical_profiles sp
),

-- Stage 2b: Statistical Quality Metrics (for outliers)
quality_metrics AS (
    SELECT
        sqm.column_id,
        sqm.iqr_outlier_ratio,
        sqm.benford_compliant,
        sqm.iqr_outlier_ratio,
        sqm.isolation_forest_anomaly_ratio,
        sqm.quality_data
    FROM statistical_quality_metrics sqm
),

-- Stage 3: Semantic Annotations
semantic AS (
    SELECT
        sa.column_id,
        sa.semantic_role,
        sa.entity_type,
        sa.business_name,
        sa.business_description,
        sa.business_concept,
        sa.confidence AS semantic_confidence,
        sa.annotation_source
    FROM semantic_annotations sa
),

-- Stage 4: Entropy Objects (pivoted by dimension)
entropy_business_meaning AS (
    SELECT
        REPLACE(REPLACE(eo.target, 'column:kontobuchungen.', ''), 'column:', '') AS column_name,
        eo.score AS entropy_business_meaning, eo.confidence AS business_meaning_confidence, eo.evidence AS business_meaning_evidence, eo.resolution_options AS business_meaning_resolution_options
    FROM entropy_objects eo
    WHERE eo.layer = 'semantic' AND eo.dimension = 'business_meaning'
),

entropy_units AS (
    SELECT
        REPLACE(REPLACE(eo.target, 'column:kontobuchungen.', ''), 'column:', '') AS column_name,
        eo.score AS entropy_units, eo.confidence AS units_confidence, eo.evidence AS units_evidence, eo.resolution_options AS units_resolution_options
    FROM entropy_objects eo
    WHERE eo.layer = 'semantic' AND eo.dimension = 'units'
),

entropy_temporal AS (
    SELECT
        REPLACE(REPLACE(eo.target, 'column:kontobuchungen.', ''), 'column:', '') AS column_name,
        eo.score AS entropy_temporal, eo.confidence AS temporal_confidence, eo.evidence AS temporal_evidence, eo.resolution_options AS temporal_resolution_options
    FROM entropy_objects eo
    WHERE eo.layer = 'semantic' AND eo.dimension = 'temporal'
),

entropy_dimensional AS (
    SELECT
        REPLACE(REPLACE(eo.target, 'column:kontobuchungen.', ''), 'column:', '') AS column_name,
        eo.score AS entropy_dimensional, eo.confidence AS dimensional_confidence, eo.evidence AS dimensional_evidence, eo.resolution_options AS dimensional_resolution_options
    FROM entropy_objects eo
    WHERE eo.layer = 'semantic' AND eo.dimension = 'dimensional'
),

entropy_derived AS (
    SELECT
        REPLACE(REPLACE(eo.target, 'column:kontobuchungen.', ''), 'column:', '') AS column_name,
        eo.score AS entropy_derived_values, eo.confidence AS derived_confidence, eo.evidence AS derived_evidence, eo.resolution_options AS derived_resolution_options
    FROM entropy_objects eo
    WHERE eo.layer = 'computational' AND eo.dimension = 'derived_values'
),

entropy_types AS (
    SELECT
        REPLACE(REPLACE(eo.target, 'column:kontobuchungen.', ''), 'column:', '') AS column_name,
        eo.score AS entropy_types, eo.confidence AS types_confidence, eo.evidence AS types_evidence, eo.resolution_options AS types_resolution_options
    FROM entropy_objects eo
    WHERE eo.layer = 'structural' AND eo.dimension = 'types'
),

entropy_outliers AS (
    SELECT
        REPLACE(REPLACE(eo.target, 'column:kontobuchungen.', ''), 'column:', '') AS column_name,
        eo.score AS entropy_outliers, eo.confidence AS outliers_confidence, eo.evidence AS outliers_evidence, eo.resolution_options AS outliers_resolution_options
    FROM entropy_objects eo
    WHERE eo.layer = 'value' AND eo.dimension = 'outliers'
),

-- Stage 5: Entropy Interpretations
interpretations AS (
    SELECT
        ei.column_name,
        ei.composite_score,
        ei.readiness,
        ei.explanation, ei.assumptions_json, ei.resolution_actions_json
    FROM entropy_interpretations ei
    WHERE ei.table_name = 'kontobuchungen'
    AND ei.column_name IS NOT NULL
)

-- Final joined result
SELECT
    b.column_name,

    NULL AS "Typing Phase",
    t.resolved_type,
    tc.parse_success_rate,

    NULL AS "Statistics Phase",
    s.null_ratio,
    s.cardinality_ratio,
    s.distinct_count,

    NULL AS "Quality Metrics (outlier input)",
    qm.iqr_outlier_ratio,
    qm.benford_compliant,
    qm.iqr_outlier_ratio,
    qm.isolation_forest_anomaly_ratio,
    qm.quality_data,

    NULL AS "Semantic Phase",
    sem.semantic_role,
    sem.entity_type,
    sem.business_name,
    sem.business_concept,
    SUBSTR(sem.business_description, 1, 50) AS business_desc_preview,
    sem.semantic_confidence,

    NULL AS "Entropy Scores",
    ROUND(ebm.entropy_business_meaning, 3) AS ent_business_meaning,
    ebm.business_meaning_confidence,
    ebm.business_meaning_evidence,
    ebm.business_meaning_resolution_options,
    ROUND(eu.entropy_units, 3) AS ent_units,
    eu.units_confidence,
    eu.units_evidence,
    eu.units_resolution_options,
    ROUND(et.entropy_temporal, 3) AS ent_temporal,
    et.temporal_confidence,
    et.temporal_evidence,
    et.temporal_resolution_options,
    ROUND(ed.entropy_dimensional, 3) AS ent_dimensional,
    ed.dimensional_confidence,
    ed.dimensional_evidence,
    ed.dimensional_resolution_options,
    ROUND(edr.entropy_derived_values, 3) AS ent_derived,
    edr.derived_confidence,
    edr.derived_evidence,
    edr.derived_resolution_options,
    ROUND(ety.entropy_types, 3) AS ent_types,
    ety.types_confidence,
    ety.types_evidence,
    ety.types_resolution_options,
    ROUND(eout.entropy_outliers, 3) AS ent_outliers,
    eout.outliers_confidence,
    eout.outliers_evidence,
    eout.outliers_resolution_options,

    NULL AS "Interpretation",
    ROUND(i.composite_score, 3) AS composite_score,
    i.explanation,
    i.assumptions_json,
    i.resolution_actions_json,
    i.readiness

FROM base b
LEFT JOIN typing t ON b.column_id = t.column_id
LEFT JOIN type_candidates_agg tc ON b.column_id = tc.column_id
LEFT JOIN statistics s ON b.column_id = s.column_id
LEFT JOIN quality_metrics qm ON b.column_id = qm.column_id
LEFT JOIN semantic sem ON b.column_id = sem.column_id
LEFT JOIN entropy_business_meaning ebm ON b.column_name = ebm.column_name
LEFT JOIN entropy_units eu ON b.column_name = eu.column_name
LEFT JOIN entropy_temporal et ON b.column_name = et.column_name
LEFT JOIN entropy_dimensional ed ON b.column_name = ed.column_name
LEFT JOIN entropy_derived edr ON b.column_name = edr.column_name
LEFT JOIN entropy_types ety ON b.column_name = ety.column_name
LEFT JOIN entropy_outliers eout ON b.column_name = eout.column_name
LEFT JOIN interpretations i ON b.column_name = i.column_name
"""

df_lineage = pd.read_sql_query(lineage_query, conn)
print(f"=== COMPLETE COLUMN LINEAGE ({len(df_lineage)} columns) ===")
display(df_lineage)

=== COMPLETE COLUMN LINEAGE (31 columns) ===

,column_name,Typing Phase,resolved_type,parse_success_rate,Statistics Phase,null_ratio,cardinality_ratio,distinct_count,Quality Metrics (outlier input),iqr_outlier_ratio,...,ent_outliers,outliers_confidence,outliers_evidence,outliers_resolution_options,Interpretation,composite_score,explanation,assumptions_json,resolution_actions_json,readiness
0,ID des Rechnungslegungsbereichs,None,BIGINT,1.000000,None,0.000000,0.000911,3,None,0.080194,...,0.802,1.0,"[{""outlier_ratio"": 0.08019441069258809, ""outli...","[{""action"": ""winsorize"", ""parameters"": {""colum...",None,0.180,This accounting area identifier has excellent ...,"[{""dimension"": ""value.outliers.outlier_rate"", ...","[{""action"": ""investigate_outlier_pattern"", ""de...",ready
1,Kontonummer des Kontos,None,BIGINT,1.000000,None,0.000000,0.110267,363,None,0.166160,...,1.000,1.0,"[{""outlier_ratio"": 0.16616038882138517, ""outli...","[{""action"": ""winsorize"", ""parameters"": {""colum...",None,0.210,This general ledger account number column has ...,"[{""dimension"": ""value.outliers.outlier_rate"", ...","[{""action"": ""add_reference_documentation"", ""de...",ready
2,Belegdatum der Buchung,None,DATE,1.000000,None,0.000000,0.024909,82,None,NaN,...,0.000,1.0,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o...",null,None,0.045,This DATE column has excellent overall data qu...,"[{""dimension"": ""semantic.temporal.time_role"", ...","[{""action"": ""add_timezone_declaration"", ""descr...",ready
3,Berichtigungs_Umsatzsteuerschlüssel,None,BIGINT,1.000000,None,0.800122,0.019757,13,None,0.060790,...,0.608,1.0,"[{""outlier_ratio"": 0.060790273556231005, ""outl...","[{""action"": ""winsorize"", ""parameters"": {""colum...",None,0.301,This VAT adjustment tax code has significant u...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""investigate_null_ratio"", ""descrip...",investigate
4,Kontonummer des Gegenkontos,None,BIGINT,1.000000,None,0.000000,0.106622,351,None,0.217801,...,1.000,1.0,"[{""outlier_ratio"": 0.2178007290400972, ""outlie...","[{""action"": ""winsorize"", ""parameters"": {""colum...",None,0.210,This offsetting account number column shows co...,"[{""dimension"": ""value.outliers.outlier_rate"", ...","[{""action"": ""investigate_outlier_pattern"", ""de...",ready
5,Buchungstext,None,VARCHAR,NaN,None,0.255468,0.158711,389,None,NaN,...,0.000,1.0,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o...",null,None,0.260,This transaction description text field has mo...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""document_null_meaning"", ""descript...",ready
6,Kontobewegung Steuersatz,None,BIGINT,1.000000,None,0.000000,0.002126,7,None,0.208080,...,1.000,1.0,"[{""outlier_ratio"": 0.2080801944106926, ""outlie...","[{""action"": ""winsorize"", ""parameters"": {""colum...",None,0.210,This tax rate column has a composite score of ...,"[{""dimension"": ""value.outliers.outlier_rate"", ...","[{""action"": ""add_unit_declaration"", ""descripti...",ready
7,EU Steuersatz,None,BIGINT,1.000000,None,0.000000,0.001823,6,None,0.010328,...,0.103,1.0,"[{""outlier_ratio"": 0.010328068043742407, ""outl...",null,None,0.077,This EU tax rate column is in excellent condit...,"[{""dimension"": ""semantic.units.unit_declaratio...","[{""action"": ""add_unit_declaration"", ""descripti...",ready
8,Belegnummer,None,BIGINT,0.933779,None,0.066221,0.106051,326,None,0.006831,...,0.068,1.0,"[{""outlier_ratio"": 0.0068314899154196486, ""out...",null,None,0.107,This document number column has low uncertaint...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""document_null_meaning"", ""descript...",ready
9,Belegfeld 2,None,BIGINT,1.000000,None,0.987242,0.142857,6,None,0.000000,...,0.000,1.0,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o...",null,None,0.210,This supplementary document field has moderate...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""document_null_meaning"", ""descript...",ready
10,Umsatz Soll,None,BIGINT,1.000000,None,0.000000,0.311968,1027,None,0.120899,...,1.000,1.0,"[{""outlier_ratio"": 0.12089914945321993, ""outli...","[{""action"": ""winsorize"", ""parameters"": {""colum...",None,0.300,This debit amount column has a composite score...,"[{""dimension"": ""semantic.units.unit_declaratio...","[{""action"": ""add_unit_declaration"", ""descripti...",investigate
11,Umsatz Haben,None,BIGINT,1.000000,None,0.000000,0.286452,943,None,0.135480,...,1.000,1.0,"[{""outlier_ratio"": 0.13547995139732685, ""outli...","[{""action"": ""winsorize"", ""parameters"": {""colum...",None,0.300,This credit amount column has moderate uncerta...,"[{""dimension"": ""semantic.units.unit_declaratio...","[{""action"": ""add_unit_declaration"", ""descripti...",investigate
12,Eingegebenr Umsatz SollHaben Kennzeichen,None,VARCHAR,1.000000,None,0.000000,0.000608,2,None,NaN,...,0.000,1.0,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o...",null,None,0.060,This debit/credit flag column has excellent da...,"[{""dimension"": ""semantic.business_meaning.nami...","[{""action"": ""add_value_set_documentation"", ""de...",ready
13,Eingegebener Umsatz,None,BIGINT,1.000000,None,0.000000,0.003949,13,None,0.011239,...,0.112,1.0,"[{""outlier_ratio"": 0.011239368165249088, ""outl...",null,None,0.169,This transaction amount column has moderate un...,"[{""dimension"": ""semantic.units.unit_declaratio...","[{""action"": ""add_unit_declaration"", ""descripti...",ready
14,WaehungsKZ Eingegebener Umsatz,None,VARCHAR,1.000000,None,0.000000,0.000911,3,None,NaN,...,0.000,1.0,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o...",null,None,0.060,This currency code column is in excellent cond...,"[{""dimension"": ""semantic.business_meaning.nami...","[{""action"": ""add_column_alias"", ""description"":...",ready
15,Umrechnungskurs,None,BIGINT,1.000000,None,0.000000,0.003038,10,None,0.011239,...,0.112,1.0,"[{""outlier_ratio"": 0.011239368165249088, ""outl...",null,None,0.169,This currency conversion rate column has low-m...,"[{""dimension"": ""semantic.units.unit_declaratio...","[{""action"": ""add_unit_declaration"", ""descripti...",ready
16,Stapelnummer,None,VARCHAR,1.000000,None,0.000000,0.009113,30,None,NaN,...,0.000,1.0,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o...",null,None,0.060,This batch identifier column is in excellent c...,"[{""dimension"": ""semantic.business_meaning.nami...","[{""action"": ""add_business_glossary"", ""descript...",ready
17,Buchungssatznummer,None,BIGINT,1.000000,None,0.000000,0.051640,170,None,0.009417,...,0.094,1.0,"[{""outlier_ratio"": 0.009416767922235723, ""outl...",null,None,0.080,This posting line number has very low uncertai...,"[{""dimension"": ""value.outliers.outlier_rate"", ...","[{""action"": ""validate_sequence_logic"", ""descri...",ready
18,Kost1Kostenstelle,None,BIGINT,1.000000,None,0.389429,0.005970,12,None,0.000000,...,0.000,1.0,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o...",null,None,0.177,This cost center column has a composite score ...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""document_null_meaning"", ""descript...",ready
19,Kennung EB-Buchung,None,BIGINT,1.000000,None,0.048299,0.000638,2,None,0.111714,...,1.000,1.0,"[{""outlier_ratio"": 0.1117140121289499, ""outlie...","[{""action"": ""winsorize"", ""parameters"": {""colum...",None,0.224,This opening balance indicator flag has modera...,"[{""dimension"": ""value.outliers.outlier_rate"", ...","[{""action"": ""recalibrate_outlier_detection"", ""...",ready
20,Wirtschaftsjahres Monat,None,BIGINT,1.000000,None,0.048299,0.000958,3,None,0.000000,...,0.000,1.0,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o...",null,None,0.074,This fiscal year month column is in excellent ...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""document_null_meaning"", ""descript...",ready
21,Bearbeitungsstatus,None,BIGINT,1.000000,None,0.048299,0.000638,2,None,0.065113,...,0.651,1.0,"[{""outlier_ratio"": 0.06511330992658794, ""outli...","[{""action"": ""winsorize"", ""parameters"": {""colum...",None,0.172,This processing status code column has a compo...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""document_null_meaning"", ""descript...",ready
22,Kontobewegungstyp,None,BIGINT,1.000000,None,0.048299,0.001277,4,None,0.028726,...,0.287,1.0,"[{""outlier_ratio"": 0.02872646026172997, ""outli...","[{""action"": ""winsorize"", ""parameters"": {""colum...",None,0.118,This transaction type classification column is...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""document_null_meaning"", ""descript...",ready
23,Rolle desw Kontos im Buchungssatz,None,BIGINT,1.000000,None,0.048299,0.000638,2,None,0.000000,...,0.000,1.0,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o...",null,None,0.074,This debit/credit role indicator has very low ...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""document_null_handling"", ""descrip...",ready
24,Folgebuchungsatzzaehler,None,BIGINT,1.000000,None,0.048299,0.000638,2,None,0.037664,...,0.377,1.0,"[{""outlier_ratio"": 0.03766358123204596, ""outli...","[{""action"": ""winsorize"", ""parameters"": {""colum...",None,0.131,This follow-up posting counter has low-moderat...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""document_null_meaning"", ""descript...",ready
25,Herkunftskennzeichen,None,VARCHAR,1.000000,None,0.048299,0.001915,6,None,NaN,...,0.000,1.0,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o...",null,None,0.074,This source system identifier column has an ex...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""add_value_set_documentation"", ""de...",ready
26,Stapelidentifikator,None,BIGINT,1.000000,None,0.048299,0.009575,30,None,0.000000,...,0.000,1.0,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o...",null,None,0.074,This batch identifier column has an excellent ...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""document_null_meaning"", ""descript...",ready
27,Belegidentifikator,None,BIGINT,1.000000,None,0.048299,0.054261,170,None,0.000000,...,0.000,1.0,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o...",null,None,0.074,This document identifier has very low uncertai...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""document_null_meaning"", ""descript...",ready
28,Leistungsdatum,None,DATE,1.000000,None,0.997570,0.250000,2,None,NaN,...,0.000,1.0,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o...",null,None,0.195,This service/delivery date column has a compos...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""investigate_null_cause"", ""descrip...",ready
29,Faelligkeitsdatum der Buchung,None,DATE,1.000000,None,0.938032,0.436275,89,None,NaN,...,0.000,1.0,"[{""outlier_ratio"": 0.0, ""outlier_count"": 0, ""o...",null,None,0.195,This payment due date column has moderate unce...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""document_null_meaning"", ""descript...",ready
30,Generalumkehr (GU),None,BIGINT,1.000000,None,0.048299,0.000638,2,None,0.001915,...,0.019,1.0,"[{""outlier_ratio"": 0.001915097350781998, ""outl...",null,None,0.078,This reversal flag has very low uncertainty (0...,"[{""dimension"": ""value.nulls.null_ratio"", ""assu...","[{""action"": ""document_null_meaning"", ""descript...",ready

In [117]:
# Styled view - highlight high entropy columns
def highlight_entropy(val):
    """Color code entropy values: green < 0.2, yellow 0.2-0.5, red > 0.5"""
    if pd.isna(val):
        return ""
    if val < 0.2:
        return "background-color: #90EE90"  # light green
    elif val < 0.5:
        return "background-color: #FFFF99"  # light yellow
    else:
        return "background-color: #FF9999"  # light red


# Apply styling to entropy columns
entropy_cols = [
    "ent_business_meaning",
    "ent_units",
    "ent_temporal",
    "ent_dimensional",
    "ent_derived",
    "ent_types",
    "composite_score",
]

styled_df = df_lineage.style.apply(
    lambda s: s.map(highlight_entropy),
    subset=[c for c in entropy_cols if c in df_lineage.columns],
)
display(styled_df)

KeyError: '`Styler.apply` and `.map` are not compatible with non-unique index or columns.'

In [118]:
# Export to CSV for further analysis
df_lineage.to_csv("./pipeline_output/column_lineage.csv", index=False)
print("Exported to ./pipeline_output/column_lineage.csv")

# Close connection
conn.close()

Exported to ./pipeline_output/column_lineage.csv